### ISSUE TITLE
readme.md still has invalid links even in sw :)

### ISSUE THREAD

**Issue by biocomp** [SoftwareNetwork/sw#1]
https://github.com/SoftwareNetwork/sw/blob/master/doc/readme.md still has some invalid links.

**Comment by egorpugin** [comment]
Doc is being tuned.

**Comment by GilesBathgate** [comment]
This is quite annoying if you land on this page from Google when looking for CPPAN docs.

**Comment by egorpugin** [comment]
Sorry, what page?
Did not understand.

**Comment by GilesBathgate** [comment]
https://github.com/SoftwareNetwork/sw/blob/master/doc/readme.md
links at bottom point to:
https://github.com/cppan/cppan/blob/master/doc/getting_started.md
Which doesn't exist.

**Comment by egorpugin** [comment]
Ok, shoule be fixed now:
- removed old info
- added link to wiki
