### ISSUE TITLE
leptonica with CLang is throwing Error 

### ISSUE THREAD

**Issue by AC0792** [SoftwareNetwork/sw#101]
D:\Sindri_Project\softwareIntegrate\leptonica\build-mingw>cmake .. -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_PREFIX_PATH=C:\Users\uie54918\.sw\storage\etc\sw\static\ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER:STRING=C:/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -DCMAKE_CXX_COMPILER:STRING=C:/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -DCMAKE_MAKE_PROGRAM=C:/Android/Sdk/ndk/21.3.6528147/prebuilt/windows-x86_64/bin/make.exe -DSW_BUILD=ON
-- The C compiler identification is Clang 9.0.8
-- The CXX compiler identification is Clang 9.0.8
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SW: D:/Sindri_Project/UserStories/sw-master-windows-client/sw.exe
-- sw: processing dependencies
Exception in file D:/dev/cppan2/client2/src/sw/driver/module.cpp:120, function operator (): error in module (C:/Users/uie54918/.sw/storage/tmp/cfg/164605/loc.sw.self.563dfb-0.0.30.dll): Exception in file D:/dev/cppan2/client2/src/sw/driver/target/native.cpp:771, function findCompiler: Cannot find compiler org.LLVM.clang->=9.0.0 <9.1.0 for settings: {"native":{"configuration":"release","library":"static","mt":"false","program":{"asm":"org.LLVM.clang->=9.0.0 <9.1.0","c":"org.LLVM.clang->=9.0.0 <9.1.0","cpp":"org.LLVM.clangpp->=9.0.0 <9.1.0","lib":"org.gnu.binutils.ar"}},"os":{"arch":"x86_64","kernel":"org.mingw"}}
sw command: D:/Sindri_Project/UserStories/sw-master-windows-client/sw.exe -static -platform x64 -compiler clang-9.0 -os mingw -d D:/Sindri_Project/softwareIntegrate/leptonica/build-mingw/.sw/cmake -config r integrate -cmake-deps D:/Sindri_Project/softwareIntegrate/leptonica/build-mingw/.sw/cmake/sw.txt -cmake-file-version 6
CMake Error at C:/Users/uie54918/.sw/storage/etc/sw/static/SWConfig.cmake:235 (message):
  sw: non-zero exit code: 1
Call Stack (most recent call first):
  CMakeLists.txt:151 (sw_execute)

 CMake Command : cmake .. -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_PREFIX_PATH=C:\Users\uie54918\.sw\storage\etc\sw\static\ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER:STRING=C:/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -DCMAKE_CXX_COMPILER:STRING=C:/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -DCMAKE_MAKE_PROGRAM=C:/Android/Sdk/ndk/21.3.6528147/prebuilt/windows-x86_64/bin/make.exe -DSW_BUILD=ON

CLang Compiler Info : 
Android (6454773 based on r365631c2) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489587874b2a325e7a516b99d838599c6f) (based on LLVM 9.0.8svn)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin

**Comment by egorpugin** [comment]
Cmake+sw for android will not work.
You can use sw only.
