### ISSUE TITLE
I tried to build something, but this error came and I couldn't get SW also

### ISSUE THREAD

**Issue by Arthurfogo7** [SoftwareNetwork/sw#102]
By not providing "FindSW.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "SW", but CMake did
  not find one.

  Could not find a package configuration file provided by "SW" with any of
  the following names:

    SWConfig.cmake
    sw-config.cmake

  Add the installation prefix of "SW" to CMAKE_PREFIX_PATH or set "SW_DIR" to
  a directory containing one of the above files.  If "SW" provides a separate
  development package or SDK, be sure it has been installed.

What I am trying to build is leptonica, but I can't do it without having there .cmake files, and I have no idea how I can get them. Building SW failed miserably for me too.

**Comment by egorpugin** [comment]
Run `sw setup` then re-run.
