### ISSUE TITLE
json.exception.parse_error.101

### ISSUE THREAD

**Issue by cstaton-ftlg** [SoftwareNetwork/sw#103]
I am trying to install tesseract according to https://github.com/tesseract-ocr/tessdoc/blob/main/Compiling.md#windows:

>Build the latest library (using Software Network client)
>1. [Download](https://software-network.org/client/sw-master-windows-client.zip) the latest SW (Software Network https://software-network.org/) client from https://software-network.org/client/.
>2. **Run sw setup** (may require administrator access)
>3. Run sw build org.sw.demo.google.tesseract.tesseract-master.

When I run "sw setup" I get this error:
>sw setup [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

I did run it as Administrator.

I am running this inside a virtual machine (Windows 7 Ultimate 64-bit (6.1, Build 7601) Service Pack 1) when I get this error. When I run "sw setup" inside my host OS (Windows 10 Pro 64-bit (10.0, Build 19044)) I do not get this error.

**Comment by cstaton-ftlg** [comment]
I do not need help with this as I was able to get tesseract installed bypassing the need for sw by using this binary

https://github.com/UB-Mannheim/tesseract/wiki

**Comment by newchapterswt** [comment]
But I met this problem too, I need to compile my own tesseract, could anyone give some help? sad ……

**Comment by egorpugin** [comment]
Hi,

I've fixed tess doc page.
Use this command instead
```
sw build org.sw.demo.google.tesseract.tesseract
```
(without `-master`).

It will build tess5.2

**Comment by mojtabaasadi** [comment]
@egorpugin  
I think the problem happens when I execute build command 
see 
```
**\Downloads> sw build org.sw.demo.google.tesseract.tesseract
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```
