### ISSUE TITLE
build self by `sw build --static` raise error

### ISSUE THREAD

**Issue by huhuang03** [SoftwareNetwork/sw#105]
**Describe the bug**
I want build sw by `sw build --static`, but an errror throws int he build.
The error is:
```
/Users/xxx/source/sw/.sw/t/184201/0bba4a/bd/build_self.generated.h:1071:71: error: use of undeclared identifier 'build_org_sw_demo_python_lib__3_10_5'; did you mean 'build_org_sw_demo_python_exe__3_10_5'?
        auto ep = std::make_unique<sw::NativeBuiltinTargetEntryPoint>(build_org_sw_demo_python_lib__3_10_5);
```
and
```
/Users/xxx/source/sw/.sw/t/184201/0bba4a/bd/build_self.generated.h:1072:18: error: use of undeclared identifier 'check_org_sw_demo_python_lib__3_10_5'; did you mean 'check_org_sw_demo_python_exe__3_10_5'?
        ep->cf = check_org_sw_demo_python_lib__3_10_5;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 check_org_sw_demo_python_exe__3_10_5
```

**To Reproduce**
1. clone sw
2. run `sw build --static` in sw.

**Information:**
 - Paste `sw --version` output.
sw.client.sw version 1.0.0
git revision 1ebf68ac9eabd93a97b759f368dd251ce833ce17
assembled on
13.08.2022 19:06:24 UTC
14.08.2022 03:06:24 CST

 - Write OS, its version (host/target)
 masOs Monterey (version 12.5.1 (21G83))
 - Describe your compiler, its version
 gcc:
```
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by egorpugin** [comment]
Yes, I also saw this spurious error. On some system it happens, on some it does not.
You need manually to replace that var.

I'll try to check possible fixes.

**Comment by egorpugin** [comment]
Possible fix is uploaded.
