### ISSUE TITLE
Newest libraries opencv-gdal seem broken

### ISSUE THREAD

**Issue by Ottunger** [SoftwareNetwork/sw#108]
**Describe the bug**
Newest sw downloaded.
Since libraries were updated, previous build fail with error below:
```
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:840, function execute1: When executing: [org.sw.demo.intel.opencv.imgcodecs-4.6.0]/modules/imgcodecs/src/loadsave.cpp
In file included from C:/Users/Ottunger/.sw/storage/pkg/71/8f/ac01/src/sdir/modules/imgcodecs/src/loadsave.cpp:47:
In file included from C:/Users/Ottunger/.sw/storage/pkg/71/8f/ac01/src/sdir/modules/imgcodecs/src/grfmts.hpp:58:
In file included from C:/Users/Ottunger/.sw/storage/pkg/71/8f/ac01/src/sdir/modules/imgcodecs/src/grfmt_gdal.hpp:56:
In file included from C:/Users/Ottunger/.sw/storage/pkg/1d/ab/255c/src/sdir/gcore/gdal_priv.h:61:
C:/Users/Ottunger/.sw/storage/pkg/1d/ab/255c/src/sdir/gcore/gdal.h:44:10: fatal error: 'gdal_version.h' file not found
#include "gdal_version.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
command failed: exit code = 1
command is copied to C:\Users\Ottunger\Desktop\dev\satoris-ocr\.sw\rsp\10763957205095555198.bat
```

And the contents of the command file:
```
@echo off

setlocal

echo [org.sw.demo.intel.opencv.imgcodecs-4.6.0]/modules/imgcodecs/src/loadsave.cpp

cd C:\Users\Ottunger\.sw\storage\pkg\71\8f\ac01\obj\bld\284492\obj

"C:/Users/Ottunger/Desktop/dev/cmdline-tools/sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android21-clang++.cmd" "@C:/Users/Ottunger/Desktop/dev/satoris-ocr/.sw/rsp/10763957205095555198.rsp" %*

if %ERRORLEVEL% NEQ 0 echo Error code: %ERRORLEVEL% && exit /b %ERRORLEVEL%
```

**Expected behavior**
Build would continue to work.

**To Reproduce**
This happens after sw auto upgraded libraries version, I guess minor version?

We do not fix version:
```
t += "org.sw.demo.intel.opencv.imgcodecs"_dep;
t += "org.sw.demo.intel.opencv.video"_dep;
t += "org.sw.demo.intel.opencv.videoio"_dep;
t += "org.sw.demo.google.tesseract.libtesseract"_dep;
```
Maybe a rollback of version would be enough?

**Information:**
 - Paste `sw --version` output.
```
C:\Users\Ottunger>sw --version
sw.client.sw version 1.0.0
git revision 0807fe6f4a866678fa022a53ffd26532e49da15f
assembled on
23.11.2022 18:53:31 UTC
23.11.2022 19:53:31 W. Europe Standard Time
```
 - Write OS, its version (host/target)
Host: windows 10 x64
Target: android armv8
 - Describe your compiler, its version
Android NDK 25.0.8775105
 - (optional, nix systems) Post backtrace if you know how to (using gdb, lldb).
 - (optional) Post sw logs using `-trace` parameter.
[sw.log](https://github.com/SoftwareNetwork/sw/files/10083133/sw.log)

**Comment by Ottunger** [comment]
Update:

In this directory C:\Users\Ottunger\.sw\storage\pkg\1d\ab\255c\src\sdir\gcore
If I copy the file `gdal_version.h.in` to `gdal_version.h` , and keep both, the build succeeds.

**Comment by Ottunger** [comment]
Probably has something to do with the configure script of the library:
<img width="1044" alt="gcore" src="https://user-images.githubusercontent.com/3816312/203759538-1b59e052-01fc-4d91-bb67-4cfcac7e7546.PNG">

**Comment by Ottunger** [comment]
Should we ping them about this? How?

**Comment by egorpugin** [comment]
No, I fixed sw package.
