### ISSUE TITLE
Linux executable is not named `sw`

### ISSUE THREAD

**Issue by nelimee** [SoftwareNetwork/sw#11]
**Describe the bug**
The linux executable provided [here](https://github.com/SoftwareNetwork/binaries/blob/master/sw-master-linux-client.tar.gz) is named `sw.client.sw-0.3.1` instead of simply `sw`.

The direct implication (that you no longer type `sw` but `sw.client.sw-0.3.1`) can be fixed by renaming the executable, but the name of the executable seems to be hard-coded when performing a `-self-upgrade`, which leads to a filesystem error on linux:
```
sw -self-upgrade                                                                                                                                                                                                   
Downloading signature file
Downloading the latest client
Unpacking
filesystem error: cannot set permissions [/tmp/sw.bak/sw]
```
The only file in `/tmp/sw.bak/` is `sw.client.sw-0.3.1`, not `sw`, so `/tmp/sw.bak/sw` does not exist and permissions cannot be set.

**Expected behavior**
The downloaded executable should be named `sw`.

**To Reproduce**
1. Download the latest binary (bug on Linux, I did not test for other distributions).
2. Move it in your PATH
3. `sw -self-upgrade`

**Information:**
 - Paste `sw --version` output.
```
sw.client.sw version 0.3.1
git revision 07b9e5859a14e80fb1bd4ed06fe0f8161afcf915 plus 5 modified files
assembled on 01.10.2019 16:56:25 CEST
```
 - Write OS, its version (host/target)
```
Manjaro 18.10 KDE Plasma.
Based on Archlinux.
```
 - Write your compiler, its version: `gcc 9.1.0`

**Comment by egorpugin** [comment]
Yes, I noticed it too, when started my tests. :)

**Comment by egorpugin** [comment]
Fixed.
