### ISSUE TITLE
Exception when executing: sw build org.sw.demo.google.tesseract.tesseract

### ISSUE THREAD

**Issue by xiehuangpeng** [SoftwareNetwork/sw#111]
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:840, function execute1: When executing: [pub.egorpugin.primitives.command-0.3.1]/src/command.cpp
C:/Users/Loading/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(142): error C2039: "contains":  "std::basic_string<char,std::char_traits<char>,std::allocator<char>>" ĳԱ
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(4871): note: μstd::basic_string<char,std::char_traits<char>,std::allocator<char>>
C:/Users/Loading/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): note: 鿴ڱĺ ģ ʵauto primitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ()<const char(&)[6]>(_T1) const
        with
        [
            _T1=const char (&)[6]
        ]
C:/Users/Loading/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C3487: bool: зرʽƵΪͬ: ǰΪvoid
C:/Users/Loading/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(144): error C3487: bool: зرʽƵΪͬ: ǰΪvoid
C:/Users/Loading/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(144): error C2562: primitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ():voidֵ
C:/Users/Loading/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): note: μprimitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ()
C:/Users/Loading/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C2296: ||: Ƿvoid
C:/Users/Loading/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C2297: ||: ǷҲvoid

How do I fix it?

**Comment by egorpugin** [comment]
Install VS2022.
