### ISSUE TITLE
SW is needed to build SW, server down

### ISSUE THREAD

**Issue by rgrahamesp** [SoftwareNetwork/sw#116]
**Describe the bug**
Ok, maybe not really a bug, but I still can't build SW because it requires SW, which is unavailable because the server is down.

**Expected behavior**
Maybe have an SW releases here, or have an alternate way of building SW?

**To Reproduce**
1. Go to https://software-network.org/

**Information:**
Maybe the server will be back up by the time anyone reads this, but it's frustrating that SW requires SW to build and there's only one (reliable) source and it's down (don't use https and it takes you to a Russian site). Could release builds also be posted here?

**Comment by egorpugin** [comment]
Hi, I have binaries here.
https://github.com/SoftwareNetwork/binaries

Server should be back soon.
