### ISSUE TITLE
ABSL file not found

### ISSUE THREAD

**Issue by sodmlx2** [SoftwareNetwork/sw#119]
Hi!

I´m compile the SW (SoftwareNetwork) on windows 11, using this command:

```
sw.exe build -static
```
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:840, function execute1: When executing: [org.sw.demo.google.re2-2023.9.1]/re2/dfa. cc
C:/Users/.sw/storage/pkg/ec/47/f871/src/sdir/re2/dfa.cc(36): 
fatal error C1083: Unable to open file include: 'absl/base /call_once.h': No such file or directory
command failed: exit code = 2 Total errors: 1

I installed the package: abseil, using VCPKG.

** System Information **
sw.client.sw version 1.0.0
git revision 30611200c2168a3ca7f9d888c11ba375b4667d07
assembled on

**Comment by egorpugin** [comment]
Please try again.

**Comment by sodmlx2** [comment]
hi!

works fine now! ;) thx

PS C:\Users\marco.silva\sw\.sw\out\176899> .\sw.client.sw-1.0.0.exe --help
OVERVIEW: SW: Software Network Client

  SW is a Universal Package Manager and Build System

  Documentation: https://software-network.org/client/sw.pdf

USAGE: sw.client.sw-1.0.0.exe [subcommand] [options]
