### ISSUE TITLE
Windows 7 Issues

### ISSUE THREAD

**Issue by tryonlinux** [SoftwareNetwork/sw#12]
Am I correct in assuming this does not work on Windows 7? I get the below error when trying to init as well as compile tesseract OCR. It occurs instantly. 

I have VS 2019 Enterprise Edition and Win 7 SP1 

Error: 
The procedure entry point DeriveAppContainerSidFromAppContainerName could not be located in the dynamic link library USERENV.dll. 

Looks like the min supported version on MSDN is possibly Win 8?

https://docs.microsoft.com/en-us/windows/win32/api/userenv/nf-userenv-deriveappcontainersidfromappcontainername

**Comment by egorpugin** [comment]
Hi, I'll fix this. Also noticed it before.

**Comment by tryonlinux** [comment]
Ah okay. Thank you! I appreciate it :)

**Comment by egorpugin** [comment]
Possible fix is in 797a7ab4.
Please, update sw and try again.

**Comment by dwickern** [comment]
I have the same error on the build dated 10-Nov-2019 15:24

**Comment by egorpugin** [comment]
Strange. Update sw now.

**Comment by dwickern** [comment]
Thanks, it's working now with 12-Nov-2019 18:04

**Comment by tryonlinux** [comment]
Works perfectly now. Thank you very much!!!
