### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by Rudzyansky** [SoftwareNetwork/sw#122]
**Describe the bug**
You have an expired certificate on software-network.org. Expires in Mon, 13 Nov 2023 11:49:57 GMT
Exception in file D:/dev/primitives/src/http/src/http.cpp:300, function download_file: url = https://software-network.org/static/specification.json, curl error: SSL connect error

**Expected behavior**
Staring build

**To Reproduce**
1. git clone https://github.com/SoftwareNetwork/sw
2. cd sw
3. sw build -static

**Information:**
 - A clean install

**Comment by egorpugin** [comment]
Thank you!
