### ISSUE TITLE
windows tesseract build error (the error is on the SW side)

### ISSUE THREAD

**Issue by vadiks2003** [SoftwareNetwork/sw#123]
**Describe the bug**
when building https://github.com/tesseract-ocr/tesseract i get an error [error.txt](https://github.com/SoftwareNetwork/sw/files/13531879/error.txt)

**Expected behavior**
i expect for tesseract to compile without errors

**To Reproduce**
1. download https://github.com/tesseract-ocr/tesseract 
2. download sw NOT a gui version for windows
3. either put a sw.exe inside tesseract folder or have it in one of PATH folders
4. sw build
5. error

**Information:**
 - Paste `sw --version` output.
sw.client.sw version 1.0.0
git revision ad5ab37cf173665c4937b4f1349fb19f733b7e9a
assembled on
17.10.2023 20:05:05 UTC
17.10.2023 23:05:05 FLE Daylight Time

 - Write OS, its version (host/target)
windows build is 19045.3693, version 22H2 Windows 10 Pro N
 - Describe your compiler, its version
i don't know what sw build exactly does, but running cmake does the entire thing use sw again and it says "
[cmake output.txt](https://github.com/SoftwareNetwork/sw/files/13531901/cmake.output.txt)
" following with error sent in the previous text file in the "describe the bug" section
 - (optional, nix systems) Post backtrace if you know how to (using gdb, lldb).
 - (optional) Post sw logs using `-trace` parameter.
[trace argument output.txt](https://github.com/SoftwareNetwork/sw/files/13531917/trace.argument.output.txt)

**Comment by egorpugin** [comment]
Hi,

The latest VS (or VS Build Tools) is required for sw to work.

It seems you have VS2019 or early VS2022.
Try to upgrade it or install latest VS Build Tools (they are probably free).
