### ISSUE TITLE
sw setup failed

### ISSUE THREAD

**Issue by YouSyd** [SoftwareNetwork/sw#128]
download the sw client and try to install on windows 10.
change the path to the sw.exe folder, open the prompt,
type in > sw setup

the output:
sw setup
Downloading database from origin remote
Exception in file D:/dev/primitives/src/http/src/http.cpp:300, function download_file: url = https://github.com/SoftwareNetwork/database/archive/master.zip, curl error: SSL connect error

 - `sw --version` output.
 sw.client.sw version 1.0.0
git revision 9081a857f713f0ffdcb61092ed2fb8c23704da6f
assembled on
17.02.2024 13:42:11 UTC
17.02.2024 21:42:11 й׼ʱ
 
 - Write OS, its version (host/target)
 Microsoft Windows [Version 10.0.19045.4170]

**Comment by egorpugin** [comment]
Try using with proxy or with '--ignore-ssl-checks' option.

**Comment by YouSyd** [comment]
thank you. `--ignore-ssl-checks` works.
