### ISSUE TITLE
Leptonica Build error for dynamic Library

### ISSUE THREAD

**Issue by ganeshchavan88** [SoftwareNetwork/sw#129]
Not able to locate below files in SW package and causing LNK1181 error,

C:\Users\Admin\.sw\storage\pkg\89\dc\64e7\obj\bld\118650\lib\org.sw.demo.gif-5.2.1.lib
C:\Users\Admin\.sw\storage\pkg\a6\70\dfa3\obj\bld\118650\lib\org.sw.demo.glennrp.png-1.6.43.lib
C:\Users\Admin\.sw\storage\pkg\46\e8\7780\obj\bld\118650\lib\org.sw.demo.tiff-4.6.0.lib
C:\Users\Admin\.sw\storage\pkg\0e\91\e874\obj\bld\118650\lib\org.sw.demo.webmproject.webp-1.3.2.lib
C:\Users\Admin\.sw\storage\pkg\aa\09\0b6b\obj\bld\118650\lib\org.sw.demo.uclouvain.openjpeg.openjp2-2.5.2.lib
C:\Users\Admin\.sw\storage\pkg\d4\ae\cb0b\obj\bld\118650\lib\org.sw.demo.jpeg-9.6.0.lib
C:\Users\Admin\.sw\storage\pkg\22\80\34d3\obj\bld\118650\lib\org.sw.demo.madler.zlib-1.3.1.lib
C:\Users\Admin\.sw\storage\pkg\d9\1e\2f98\obj\bld\118650\lib\org.sw.demo.xz_utils.lzma-5.4.5.lib
C:\Users\Admin\.sw\storage\pkg\25\78\4a4d\obj\bld\118650\lib\org.sw.demo.mgk25.jbig.jbig-2.1.0.lib
C:\Users\Admin\.sw\storage\pkg\60\89\7ba0\obj\bld\118650\lib\org.sw.demo.mgk25.jbig.ar-2.1.0.lib
C:\Users\Admin\.sw\storage\pkg\13\9d\bdef\obj\bld\118650\lib\org.sw.demo.facebook.zstd.zstd-1.5.6.lib

tried after update SW package but the error is same.

**Comment by egorpugin** [comment]
How do you invoke build?
Need more info on everything.

**Comment by ganeshchavan88** [comment]
Followed below steps for build,

1. sw --self-upgrade
2. sw setup
3. clone by using - git clone https://github.com/danbloomberg/leptonica leptonica 
4.  mkdir build && cd build 
5. cmake .. -DBUILD_SHARED_LIBS=ON -A Win32

After above steps trying to build it using VS2022 but it shows the errors mentioned previously.

**Comment by ganeshchavan88** [comment]
Any comments on above?

**Comment by egorpugin** [comment]
Hi,

I tried your workflow when you posted it, it works for me.
Probably already fixed on the master branch.
So I'm trying to push a new release (binaries).

Please wait (2-3 days). I'll make a ping here.

**Comment by egorpugin** [comment]
Ok, I've updated sw binaries.
Run `sw --self-upgrade` and try again. Try to remove cmake binary dir completely and make it again.

**Comment by ganeshchavan88** [comment]
Thanks a lot. it worked for me.
