### ISSUE TITLE
no target loaded

### ISSUE THREAD

**Issue by zcshsh** [SoftwareNetwork/sw#13]
**Describe the bug**
when I use cmake to build tesseract with SW, there was an exception

**Expected behavior**
Exception in file D:\dev\cppan2\client2\src\sw\core\build.cpp:228, function
  loadPackages: loc.sw.self.472d1f-local: No target loaded:
  com.Microsoft.Windows.SDK.ucrt-*

**To Reproduce**
sw command: F:/sw.exe -shared -platform x86 -d G:/study/tesseract_UB-Mannheim_5.0/build/.sw/cmake integrate -cmake-deps G:/study/tesseract_UB-Mannheim_5.0/build/.sw/cmake/sw.txt
CMake Error at C:/Users/DW/.sw/storage/etc/sw/static/SWConfig.cmake:127 (message):
  sw: non-zero exit code: 1:

  out:

  

  err:

  Exception in file D:\dev\cppan2\client2\src\sw\core\build.cpp:228, function
  loadPackages: loc.sw.self.472d1f-local: No target loaded:
  com.Microsoft.Windows.SDK.ucrt-*
Call Stack (most recent call first):
  CMakeLists.txt:206 (sw_execute)

**Information:**
 how can I resolve this question, because there is not D: in my computer.

**Comment by egorpugin** [comment]
Do you have WinSDK installed?

> how can I resolve this question, because there is not D: in my computer.

It's not about your computer. It is debug information.

**Comment by zcshsh** [comment]
> Do you have WinSDK installed?
> 
> > how can I resolve this question, because there is not D: in my computer.
> 
> It's not about your computer. It is debug information.

yes, my system is win10, I have installed winsdk, and what is the mean of the debug information, I should install cppan, isn't it?

**Comment by egorpugin** [comment]
> I should install cppan, isn't it?

No, you should not.

Could you run your command with `-trace` parameter and attach the log here? Like `sw -trace *rest of args*`.

**Comment by egorpugin** [comment]
I think I found the issue, will notify you later.

**Comment by egorpugin** [comment]
I've updated sw. Try it now.
`sw --self-upgrade` or re-download from the website.

**Comment by egorpugin** [comment]
I've updated sw client. Try it now.
`sw --self-upgrade` or re-download from the website.
