### ISSUE TITLE
Failed to run "sw setup"

### ISSUE THREAD

**Issue by kimvnhung** [SoftwareNetwork/sw#132]
**Describe the bug**
 sw setup --trace
----------------------------------------
Starting sw...
version:
sw.client.sw version 1.0.0
git revision c6b731a48ee4660a922b0f9c140c8e24edac234a
assembled on
30.05.2024 19:29:15 UTC
31.05.2024 02:29:15 SE Asia Standard Time
command line:
C:\Program Files (x86)\sw\sw.exe setup --trace
Exception in file D:/dev/primitives/src/http/src/http.cpp:301, function download_file: url = https://software-network.org/static/specification.json, curl error: SSL connect error

It seems https://software-network.org has an expired certificate

**Information:**
 - I'm working on Windows 10

**Comment by kimvnhung** [comment]
Sorry, this dupplicate here https://github.com/SoftwareNetwork/sw/issues/128

**Comment by egorpugin** [comment]
Should be fixed.
