### ISSUE TITLE
Allow the user to define a specific bin output directory

### ISSUE THREAD

**Issue by Telokis** [SoftwareNetwork/sw#17]
The current behavior of `sw` is to output bin files to `.sw/out/<hash>/`.  
This is not ideal because the user doesn't know the value of `<hash>`. We have to look at the build output to see where the file was outputted.  

My suggestion is to add a CLI option like `--out-dir` which could be set to any directory (existing or not). `sw` would then output everything there.  
This could also be specified inside the `sw.cpp`, allowing for consistent setup without relying on the user to remember to use the CLI option.

We could also have both a CLI option and a `sw.cpp` config but the CLI option takes precedence, for example.

**Comment by egorpugin** [comment]
Added `sw build --output-dir bin`.
Update sw and try it!

**Comment by Telokis** [comment]
Works perfectly, thank you!

**Comment by Telokis** [comment]
Are you considering the other part of the issue?

> This could also be specified inside the sw.cpp, allowing for consistent setup without relying on the user to remember to use the CLI option.
> 
> We could also have both a CLI option and a sw.cpp config but the CLI option takes precedence, for example.

**Comment by egorpugin** [comment]
Such thing was earlier (also in cppan). It disabled at the moment.
