### ISSUE TITLE
'driver' build fails because "PackageId 'org.sw.demo.madler.zlib' not found"

### ISSUE THREAD

**Issue by biocomp** [SoftwareNetwork/sw#2]
I guess it's missing in packages.db?

**Comment by egorpugin** [comment]
I saw one issue when server is not found (we don't have one public yet), sw fails.
Is it your issue?

**Comment by egorpugin** [comment]
For `org.sw.demo.madler.zlib` see (first line):
https://github.com/SoftwareNetwork/database/blob/master/package.csv

**Comment by biocomp** [comment]
Looks like something is wrong with packages.db. 

I see that csv is downloaded correctly, then I see that data is being transferred to the database after download, and it includes the package. But then inside PackagesDatabase::findDependencies, code fails to find that package in the same database. Not sure if it's something with SQL, mysql, database or something else.
 
I don't think it's because server is not public, but obviously I could be wrong.

Failure is here (q.empty() is true):
```
        auto q = (*db)(
            custom_query(sqlpp::verbatim("SELECT package_id FROM package WHERE path = '" + dep.ppath.toString() + "' COLLATE NOCASE"))
            .with_result_type_of(select(pkgs.packageId).from(pkgs))
            );
        //auto q = (*db)(select(pkgs.packageId).from(pkgs).where(pkgs.path == dep.ppath.toString()));
        if (q.empty())
            // TODO: replace later with typed exception, so client will try to fetch same package from server
            throw std::runtime_error("PackageId '" + project.ppath.toString() + "' not found.");
```

But, if it's too early to be trying I guess I'll stop :)
