### ISSUE TITLE
Packages: no entry point for org.sw.demo.jbeder.yaml_cpp-master

### ISSUE THREAD

**Issue by Telokis** [SoftwareNetwork/sw#20]
Running `sw build --output-dir bin` triggers an error

```
Exception in file D:\dev\cppan2\client2\src\sw\core\build.cpp:314, function loadPackages: no entry point for org.sw.demo.jbeder.yaml_cpp-master
```

Even after self-upgrading and cleaning the storage.

**Comment by egorpugin** [comment]
Try to update the client and try again.
I updated yaml library, so new client must be deployed.
(I'm investigating the stability issues on such cases.)

**Comment by Telokis** [comment]
Ok, that did the trick, thank you!  
Do you think there is anything we could do to prevent this kind of issues? The fact that updating completely prevents the usage of SW is quite a strong constraint since nothing can be done until you fix it manually

**Comment by egorpugin** [comment]
> Do you think there is anything we could do to prevent this kind of issues?

Not yet. This issue is postponed, until I implement some other architecture improvements.

**Comment by egorpugin** [comment]
Ok, found possible solution.
It won't require downloading tons of stuff if you do not use external packages. It also allows you to work in offline mode in same case.

Maybe I'll add a fallback to current

**Comment by egorpugin** [comment]
The solution is not very reliable and way too complex. :(
It will be used in offline mode. But it will be implemented later with better sw distribution (probably msi installer and deb/rpm packages).

**Comment by egorpugin** [comment]
Specifically this one is fixed now.
