### ISSUE TITLE
 sw --self-upgrade fails

### ISSUE THREAD

**Issue by Moldoteck** [SoftwareNetwork/sw#22]
When i do
`sw --self-upgrade`
i get this error:
```
Downloading signature file
Downloading the latest client
Downloaded bad file (signature check failed): Exception in file D:\dev\cppan2\client\src\sw\client\sig.h:117, function ds_verify_file: Bad digital signature
```

System: Windows 10 x64

sw.client.sw version 1.0.0
git revision 76ca21197708ddd6245b5775655d45bb5ee3598f
assembled on 12.02.2020 02:00:56 GTB Standard Time

using VS 2019

**Comment by egorpugin** [comment]
Fixed, thank you!
There was publishing pipeline error.
I've added a check, so upload errors should be visible to me next time.
