### ISSUE TITLE
sw setup command results in error

### ISSUE THREAD

**Issue by Moldoteck** [SoftwareNetwork/sw#23]
When i use sw setup, i get this error
Downloading database from origin remote
copy_file: The system cannot find the path specified.: "C:\Users\MyUser\AppData\Local\Temp\sw\9987-739f-9422-7233\database-master\schema.version", "C:\Users\MyUser\ .sw\storage\etc\sw\database\1\remote\origin\repository\schema.version"

System: Win 10
SW version: 
sw.client.sw version 1.0.0
git revision 659c9cd80fe1a83c46fa32be83b8f09919c78d2a
assembled on 12.02.2020 15:10:40 GTB Standard Time

MVSC

**Comment by egorpugin** [comment]
Try to remove `C:\Users\MyUser\ .sw\storage\etc\sw\database\1\remote` and re-run.
Sometimes sw cannot update remote db.

**Comment by Moldoteck** [comment]
Not working

**Comment by egorpugin** [comment]
Try to remove `C:\Users\MyUser\AppData\Local\Temp\sw` also.
Does `sw setup` require admin privileges from you?

**Comment by Moldoteck** [comment]
Not working too
I think not. Anyway my cmd always runs as admin

**Comment by egorpugin** [comment]
```
copy_file: The system cannot find the path specified.: "C:\Users\MyUser\AppData\Local\Temp\sw\9987-739f-9422-7233\database-master\schema.version", "C:\Users\MyUser\ .sw\storage\etc\sw\database\1\remote\origin\repository\schema.version"
```

Do you have both of these files?
What is your username? Maybe it has spaces in it? Unicode symbols?

I do not have good versions for now, need to think what's the problem.

**Comment by Moldoteck** [comment]
Temp has all the files, but C:\Users\MyUser\.sw\storage\etc\sw\database\1\remote\origin has only packages.db and packages.db.lock. repository directory doesn't exist.
User name does not have spaces/unicode symbols

**Comment by egorpugin** [comment]
Try to run `sw -trace setup` and post log here.

**Comment by Moldoteck** [comment]
----------------------------------------
Starting sw...
command line:
sw -trace setup
Packages database was not found
Downloading database from origin remote
copy_file: The system cannot find the path specified.: "C:\Users\AFCJEJK\AppData\Local\Temp\sw\e5fc-7553-4c60-8e68\database-master\schema.version", "C:\Users\AFCJEJK\.sw\storage\etc\sw\database\1\remote\origin\repository\schema.version"

**Comment by egorpugin** [comment]
```"C:\Users\AFCJEJK.sw\s...```
Do you fix your username somehow or is it really no backslash before `.sw`?

**Comment by Moldoteck** [comment]
there is backslash, but github is masking it

**Comment by Moldoteck** [comment]
The strange thing is that yesterday it worked, but i re-installed sw and now it doesn't work

**Comment by Moldoteck** [comment]
```
----------------------------------------
Starting sw...
command line:
sw -trace setup
Packages database was not found
Downloading database from origin remote
copy_file: The system cannot find the path specified.: "C:\Users\AFCJEJK\AppData\Local\Temp\sw\e5fc-7553-4c60-8e68\database-master\schema.version", "C:\Users\AFCJEJK\.sw\storage\etc\sw\database\1\remote\origin\repository\schema.version"
```

**Comment by egorpugin** [comment]
Ok, what if you remove `.sw\storage\etc\sw\database`?
(This will cause to re-download all packages, but we need to check it.)

Next step is to remove `.sw\storage` completely.
Next - remove whole `.sw` with settings.

You could backup your db before these actions.

**Comment by egorpugin** [comment]
Looks like bad rights on files/dirs.

**Comment by Moldoteck** [comment]
Hmm. So strange. I logged-out and logged-in back and command magically started to work. Anyway, thank you for help

**Comment by egorpugin** [comment]
Feel free to reopen.
