### ISSUE TITLE
Run SW with older dependencies

### ISSUE THREAD

**Issue by Moldoteck** [SoftwareNetwork/sw#25]
**Is your feature request related to a problem? Please describe.**
Can't use SW because it requires GLIBC 2.25, but i have 2.23(Ubuntu 16.04)

**Describe the solution you'd like**
A client that can use GLIBC 2.23

**Comment by egorpugin** [comment]
It is known problem.

I thought about:
1) building sw for ubuntu16.04 (but also we may need to build for other distros 14.04, centos6,7 - a burden),
2) building sw with static glibc, but this way require more work.

And for 1) it is necessary to make better self upgrade mechanism, what is not in near todo list.
