### ISSUE TITLE
Can't build tess example

### ISSUE THREAD

**Issue by lucaszanella** [SoftwareNetwork/sw#26]
I tried to build 

https://github.com/SoftwareNetwork/sw/tree/master/test/integrations/cmake/tess

by going into this folder and doing 

`sw build`

but I get 

`"cannot open include file: 'allheaders.h'" in main.cpp`

am I writing the wrong command?

**Comment by egorpugin** [comment]
Hi, but here you shoult invoke cmake, not sw.

```
(install sw before, add to PATH)
sw setup # call once
mkdir build && cd build && cmake .. && cmake --build .
```

**Comment by egorpugin** [comment]
The root issue is in https://github.com/SoftwareNetwork/sw/issues/28
Let's continue discussion there.
