### ISSUE TITLE
opencv2/core/utility.hpp:714:14: error: 'recursive_mutex' in namespace 'std' does not name a type

### ISSUE THREAD

**Issue by lucaszanella** [SoftwareNetwork/sw#27]
at https://github.com/SoftwareNetwork/sw/blob/master/test/integrations/cmake/tess/CMakeLists.txt

[ 50%] Building CXX object CMakeFiles/untitled.dir/main.cpp.obj
In file included from C:/Users/LZ/.sw/storage/pkg/aa/2f/bc64/src/sdir/modules/core/include/opencv2/core.hpp:3293,
                 from C:/Users/LZ/.sw/storage/pkg/3b/11/4f5f/src/sdir/modules/highgui/include/opencv2/highgui.hpp:46,
                 from C:\Users\LZ\Downloads\sw-master\sw-master\test\integrations\cmake\tess\main.cpp:7:
C:/Users/LZ/.sw/storage/pkg/aa/2f/bc64/src/sdir/modules/core/include/opencv2/core/utility.hpp:714:14: error: 'recursive_mutex' in namespace 'std' does not name a type
  714 | typedef std::recursive_mutex Mutex;
      |              ^~~~~~~~~~~~~~~
C:/Users/LZ/.sw/storage/pkg/aa/2f/bc64/src/sdir/modules/core/include/opencv2/core/utility.hpp:63:1: note: 'std::recursive_mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   62 | #include <mutex>  // std::mutex, std::lock_guard
  +++ |+#include <mutex>
   63 | #endif
C:/Users/LZ/.sw/storage/pkg/aa/2f/bc64/src/sdir/modules/core/include/opencv2/core/utility.hpp:715:29: error: 'Mutex' is not a member of 'cv'
  715 | typedef std::lock_guard<cv::Mutex> AutoLock;
      |                             ^~~~~
C:/Users/LZ/.sw/storage/pkg/aa/2f/bc64/src/sdir/modules/core/include/opencv2/core/utility.hpp:715:29: error: 'Mutex' is not a member of 'cv'
C:/Users/LZ/.sw/storage/pkg/aa/2f/bc64/src/sdir/modules/core/include/opencv2/core/utility.hpp:715:34: error: template argument 1 is invalid
  715 | typedef std::lock_guard<cv::Mutex> AutoLock;
      |                                  ^
CMakeFiles\untitled.dir\build.make:79: recipe for target 'CMakeFiles/untitled.dir/main.cpp.obj' failed
mingw32-make[2]: *** [CMakeFiles/untitled.dir/main.cpp.obj] Error 1
CMakeFiles\Makefile2:113: recipe for target 'CMakeFiles/untitled.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/untitled.dir/all] Error 2
Makefile:99: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by egorpugin** [comment]
Do you have Visual Studio?
Is it possible to build this example with it?

**Comment by egorpugin** [comment]
There is not pthread in your installation. Not sw issue.
