### ISSUE TITLE
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs

### ISSUE THREAD

**Issue by rweldin** [SoftwareNetwork/sw#29]
I receive linker warnings and errors when trying to build Leptonica and Tesseract with Visual Studio 2017. I last built both applications a couple months ago with no issues, but after I upgraded sw to the current version today I have the issues noted below.

Of note I'm using static linking of the external dependencies and am using the following cmake command: cmake -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 ..

When adding the verbose flag to my Leptonica release build the following is output:

3>Searching libraries
3>    Searching C:\.sw\storage\pkg\89\dc\64e7\obj\bld\135497\lib\org.sw.demo.gif-5.2.1.lib:
3>    Searching C:\.sw\storage\pkg\a9\0c\280b\obj\bld\135497\lib\org.sw.demo.jpeg-9.4.0.lib:
3>    Searching C:\.sw\storage\pkg\28\39\9564\obj\bld\135497\lib\org.sw.demo.glennrp.png-1.6.37.lib:
3>    Searching C:\.sw\storage\pkg\f5\fe\083c\obj\bld\135497\lib\org.sw.demo.tiff-4.1.0.lib:
3>    Searching C:\.sw\storage\pkg\79\7b\0892\obj\bld\135497\lib\org.sw.demo.webmproject.webp-1.0.3.lib:
3>    Searching C:\.sw\storage\pkg\f7\91\f458\obj\bld\135497\lib\org.sw.demo.uclouvain.openjpeg.openjp2-2.3.1.lib:
3>    Searching C:\.sw\storage\pkg\ce\99\b2f8\obj\bld\135497\lib\org.sw.demo.madler.zlib-1.2.11.lib:
3>    Searching C:\.sw\storage\pkg\76\c7\435a\obj\bld\135497\lib\org.sw.demo.facebook.zstd.zstd-1.4.4.lib:
3>    Searching C:\.sw\storage\pkg\25\78\4a4d\obj\bld\135497\lib\org.sw.demo.mgk25.jbig.jbig-2.1.0.lib:
3>    Searching C:\.sw\storage\pkg\60\89\7ba0\obj\bld\135497\lib\org.sw.demo.mgk25.jbig.ar-2.1.0.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\kernel32.lib:
3>    Searching C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64\oldnames.lib:
3>    Searching C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64\concrtd.lib:
3>    Searching C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64\msvcprtd.lib:
3>    Searching C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64\vcruntimed.lib:
3>    Searching C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64\msvcrtd.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64\ucrtd.lib:
3>    Searching C:\.sw\storage\pkg\2a\68\57cb\obj\bld\135497\lib\org.sw.demo.xz_utils.lzma-5.2.4.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\user32.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\gdi32.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\winspool.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\shell32.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\ole32.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\oleaut32.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\uuid.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\comdlg32.lib:
3>    Searching C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64\advapi32.lib:
3>    Searching C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64\MSVCRT.lib:
3>
3>Finished searching libraries
3>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library

I did not compile Tesseract with the verbose flag, but received the following error:

3>Auto build dll exports
3>msvcprtd.lib(locale0_implib.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in adaptions.obj
3>   Creating library E:/src/repo/tesseract/Win64/Release/tesseract50.lib and object E:/src/repo/tesseract/Win64/Release/tesseract50.exp
3>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library

**Information:**
 - sw.client.sw version 1.0.0, git revision 6ecf9741c6bea03eb59bf27cbce8f6f53f3165bc
 - Windows 10 x64

Please let me know if you need any additional information.

Thanks,
Ryan

**Comment by egorpugin** [comment]
> I receive linker warnings and errors when trying to build Leptonica and Tesseract with Visual Studio 2017.

How do you build it?
Please provide commands.

**Comment by rweldin** [comment]
Egor, thanks for your quick response. Below are my answers to your questions, but I only posted the linker commands for Leptonica. Please let me know if you need anything else.

1.)
mkdir win64 && cd win64
cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 ..
Then I use Visual Studio 2017 to build a release version of the DLL. The linker command line is as follows:

/OUT:"E:\src\repo\leptonica\win64\bin\Release\leptonica-1.80.0.dll" /MANIFEST /NXCOMPAT /PDB:"E:/src/repo/leptonica/win64/bin/Release/leptonica-1.80.0.pdb" /DYNAMICBASE "C:\.sw\storage\pkg\89\dc\64e7\obj\bld\135497\lib\org.sw.demo.gif-5.2.1.lib" "C:\.sw\storage\pkg\a9\0c\280b\obj\bld\135497\lib\org.sw.demo.jpeg-9.4.0.lib" "C:\.sw\storage\pkg\28\39\9564\obj\bld\135497\lib\org.sw.demo.glennrp.png-1.6.37.lib" "C:\.sw\storage\pkg\f5\fe\083c\obj\bld\135497\lib\org.sw.demo.tiff-4.1.0.lib" "C:\.sw\storage\pkg\79\7b\0892\obj\bld\135497\lib\org.sw.demo.webmproject.webp-1.0.3.lib" "C:\.sw\storage\pkg\f7\91\f458\obj\bld\135497\lib\org.sw.demo.uclouvain.openjpeg.openjp2-2.3.1.lib" "C:\.sw\storage\pkg\ce\99\b2f8\obj\bld\135497\lib\org.sw.demo.madler.zlib-1.2.11.lib" "C:\.sw\storage\pkg\76\c7\435a\obj\bld\135497\lib\org.sw.demo.facebook.zstd.zstd-1.4.4.lib" "C:\.sw\storage\pkg\25\78\4a4d\obj\bld\135497\lib\org.sw.demo.mgk25.jbig.jbig-2.1.0.lib" "C:\.sw\storage\pkg\60\89\7ba0\obj\bld\135497\lib\org.sw.demo.mgk25.jbig.ar-2.1.0.lib" "kernel32.lib" "oldnames.lib" "concrtd.lib" "msvcprtd.lib" "vcruntimed.lib" "msvcrtd.lib" "ucrtd.lib" "C:\.sw\storage\pkg\2a\68\57cb\obj\bld\135497\lib\org.sw.demo.xz_utils.lzma-5.2.4.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib" /IMPLIB:"E:/src/repo/leptonica/win64/src/Release/leptonica-1.80.0.lib" /DLL /MACHINE:X64 /INCREMENTAL:NO /PGD:"E:\src\repo\leptonica\win64\bin\Release\leptonica-1.80.0.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"leptonica.dir\Release\leptonica-1.80.0.dll.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO /TLBID:1 

Additional Options:
%(AdditionalOptions) /machine:x64

I receive the following warning/error for both Leptonica & Tesseract:

LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library

2.) I use Leptonica and Tesseract for OCR in my application. I've been building the DLLs for a few years with CPPAN and now SW.

**Comment by egorpugin** [comment]
1) Try to update sw (`sw --self-upgrade` or manually), run `sw setup`.
This will update cmake integration script in the system.
Run your commands again.

2) What is your build system? If it is cmake, then it is easy to integrate lept/tess there like in this example: https://github.com/SoftwareNetwork/sw/blob/master/test/integrations/cmake/tess/CMakeLists.txt

**Comment by egorpugin** [comment]
Also I've tested your workflow with leptonica, everything works fine as expected. I assume you have old sw/sw cmake integration.
I've added cmake integration version check, so it will notice users automatically in the future.
https://github.com/SoftwareNetwork/sw/commit/dae1dfe3f715b5da68f5cd24cf737b49ee911715#diff-6f4bb1c6a0597a0398b5992992cbed92R157

**Comment by rweldin** [comment]
I wiped my SW folders, downloaded the current SW, did sw setup, downloaded the Leptonica source again, recompiled with Visual Studio and got the same LNK4098 link warning.

I also tried the following:
cmake -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 ..
cmake --build .

The build outputs a debug DLL when I'm expecting a release version. I also tried adding -DCMAKE_BUILD_TYPE=Release, but still get a debug DLL when building with cmake; below is the output. 

    Creating library R:/leptonica-master/win64/src/Debug/leptonica-1.80.0d.lib and object R:/leptonica-master/win64/src/Debug/leptonica-1.80.0d.exp
  leptonica.vcxproj -> R:\leptonica-master\win64\bin\Debug\leptonica-1.80.0d.dll
  Building Custom Rule R:/leptonica-master/CMakeLists.txt

In researching the LNK4098 issue I saw trying to link release and debug libs can cause this issue. If you have any other suggestions please let me know. Thank you!

**Comment by egorpugin** [comment]
`cmake --build . --config Release` to build release binaries.

**Comment by egorpugin** [comment]
Run `cmake -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 .. -DSW_DEBUG=1`, it will show sw command.
Run that command manually with `-trace` argument. Post results.

**Comment by rweldin** [comment]
Below is a text document with the output. Thank you!

[trace.txt](https://github.com/SoftwareNetwork/sw/files/4335376/trace.txt)

**Comment by rweldin** [comment]
Of note I tried to compile Tesseract with cmake using the --config Release flag and the failure is noted below. [tesseract.txt](https://github.com/SoftwareNetwork/sw/files/4335510/tesseract.txt) shows the full verbose output. Hope this is helpful to you.


R:\tesseract-master\Win64>cmake -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 ..
R:\tesseract-master\Win64>cmake --build . --config Release

Auto build dll exports
msvcprtd.lib(locale0_implib.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in adaptions.obj [R:\tesseract-master\Win64\libtesseract.vcxproj]
Creating library R:/tesseract-master/Win64/Release/tesseract50.lib and object R:/tesseract-master/Win64/Release/tesseract50.exp
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [R:\tesseract-master\Win64\libtesseract.vcxproj]
R:\tesseract-master\Win64\bin\Release\tesseract50.dll : fatal error LNK1319: 1 mismatches detected [R:\tesseract-master\Win64\libtesseract.vcxproj]
tessopt.vcxproj -> R:\tesseract-master\Win64\bin\Release\tessopt.dll

**Comment by egorpugin** [comment]
Ok, confirmed, reproduced and fixed. Thank you.
`sw --self-upgrade` and try again.
