### ISSUE TITLE
Latest commit fails to build in Windows/VS 2017. Missing dependency to primitives/exceptions?

### ISSUE THREAD

**Issue by biocomp** [SoftwareNetwork/sw#3]
These are the errors I'm getting, did you forget to add dependency by any chance?

```
Error	C1083	Cannot open include file: 'primitives/exceptions.h': No such file or directory (compiling source file C:\Users\UserName\Source\Repos\sw\src\builder\db_file.cpp)	builder	C:\Users\UserName\source\repos\sw\src\builder\concurrent_map.h	10	
Error	C1083	Cannot open include file: 'primitives/exceptions.h': No such file or directory (compiling source file C:\Users\UserName\Source\Repos\sw\src\builder\file_storage.cpp)	builder	C:\Users\UserName\source\repos\sw\src\builder\concurrent_map.h	10	
Error	C1083	Cannot open include file: 'primitives/exceptions.h': No such file or directory (compiling source file C:\Users\UserName\Source\Repos\sw\src\builder\file.cpp)	builder	C:\Users\UserName\source\repos\sw\src\builder\concurrent_map.h	10	
Error	C1083	Cannot open include file: 'primitives/exceptions.h': No such file or directory (compiling source file C:\Users\UserName\Source\Repos\sw\src\builder\command.cpp)	builder	C:\Users\UserName\source\repos\sw\src\builder\concurrent_map.h	10	
```

**Comment by egorpugin** [comment]
I did not update primitives for some time.
Should be ok now.

**Comment by egorpugin** [comment]
Also I'm targeting to switch from cppan builds to sw only builds.
Sw is already self hosted for a long time, so I'm looking for smooth transition.

**Comment by egorpugin** [comment]
Sw is now built on appveyor with itself.
https://ci.appveyor.com/project/egorpugin/sw/history

It is stage 2 of bootstrap process. Hope, we'll get to stage 3 soon.

stage 1 - cppan builds sw1
stage 2 - sw1 builds sw2
stage 3 - sw2 builds sw3

I see some errors on stage3 some time ago. Currently it works fine, but I need smooth pipeline to deliver stage2 (sw2) binaries on the web in order to perform stage3.

**Comment by biocomp** [comment]
Thanks for a quick fix, I'm verifying it on my side )
