### ISSUE TITLE
Unable to find header files for external libraries - Leptonica

### ISSUE THREAD

**Issue by rweldin** [SoftwareNetwork/sw#30]
During a Leptonica build the header files for the external libraries are not found. Attached are logs from my command line [log.txt](https://github.com/SoftwareNetwork/sw/files/4341154/log.txt) and a log from a Visual Studio 2017 build [VS_log.txt](https://github.com/SoftwareNetwork/sw/files/4341156/VS_log.txt)

Also attached is a trace log [trace.txt](https://github.com/SoftwareNetwork/sw/files/4341176/trace.txt)

R:\leptonica-master\win64>sw --version
sw.client.sw version 1.0.0
git revision b2f160ed406a3efa0dd20839a9b169ba4169a949
assembled on
17.03.2020 00:54:02 UTC
16.03.2020 19:54:02 Central Daylight Time

Please let me know if you need anything else. Thanks!

**Comment by egorpugin** [comment]
True, trank you.
CMake does not understand its own old statement. I've modernized them.
