### ISSUE TITLE
Cannot link library

### ISSUE THREAD

**Issue by puRe1337** [SoftwareNetwork/sw#31]
Tried your https://github.com/SoftwareNetwork/sw/tree/master/test/integrations/cmake/tess with

> sw setup
mkdir build
cd build
cmake ..
cmake --build ..

output:

> LINK : fatal error LNK1104: Datei "com.microsoft.visualstudio.vc.libcpp-19.25.28612.lib" kann nicht geöffnet werden. (cannot open file)

I have also tried cleaning the .sw/storage folder and calling sw setup again many times but that didnt change anything. I made it able to compile after I have removed com.microsoft.* stuff from linking, but I guess thats not the meaning of using sw

**Information:**

> sw --version
sw.client.sw version 1.0.0
git revision f06a999a1673aa520e003df900b5bb328d7ec04b plus 1 modified files
assembled on
09.04.2020 18:31:11 UTC
09.04.2020 20:31:11 Mitteleurop�ische Sommerzeit

 - OS: win10 1909
 - Compiler: msvc 19.25.28612 / vs 16.5.3

**Comment by egorpugin** [comment]
Thank you!
Run `sw --self-upgrade` and try again.

**Comment by peterhhchan** [comment]
Hi, can confirms this works now.  The references to the Microsoft libraries are no longer in the VS solution.  Thank you.
