### ISSUE TITLE
Missing dependencies on Linux

### ISSUE THREAD

**Issue by nelimee** [SoftwareNetwork/sw#33]
**Describe the bug**
`sw` needs `flex` and `bison` to work and it seems to be missing from the README.

**Expected behavior**
Dependencies are written on the README or on the documentation.

**To Reproduce**
1. Get a fresh Linux (Fedora 31 in my case).
2. Download `sw` binaries and run `sw build -static` as written in the README.
3. An error message for `flex` is thrown. Once `flex` is installed, a similar error is thrown for `bison`.
```
Performing 63 check(s): pub.egorpugin.llvm_project.llvm.support_lite-master (support_lite), config 183752
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:344, function prepare: passed program 'flex' is not resolved (missing): generate: "/home/*****/.sw/storage/pkg/d2/69/81cc/obj/bld/837326/bdp/fb/range.ll/range.ll.cpp", 4236949366111544608, # of arguments 5
```

**Information:**
 - Happened to me the 11/04/2020 with a fresh version of `sw`. I updated `sw` since then...
 - Fedora 31 
```
❯ uname -a
Linux **** 5.5.17-200.fc31.x86_64 #1 SMP Mon Apr 13 15:29:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
❯ clang --version
clang version 11.0.0 (git@github.com:llvm/llvm-project.git a348de480d34257ffe394ab51b880c9aef243d80)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

**Comment by egorpugin** [comment]
Hi,

> sw needs flex and bison to work and it seems to be missing from the README.

True.
Non-windows systems need flex and bison because I did not package them for those OS yet.
I'll try to fix it.
