### ISSUE TITLE
build leptonica error

### ISSUE THREAD

**Issue by wisexie** [SoftwareNetwork/sw#35]
**Describe the bug**
build leptonica error，

I would like to ask if it is wrong to execute the pch step, he always skips on line 174, and does not execute to 187
In addition, I only have the C drive，not have the D

[174/187] [config pch]
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:631, function execute1: When executing: [config pch]

**To Reproduce**
       git clone https://github.com/danbloomberg/leptonica
          cd leptonica
          mkdir build
          cd build
          cmake ..

**Information:**
 - latest version
 - Os is Win10

**Comment by egorpugin** [comment]
Try to update sw client. You did not provide sw version, so I can't say what's wrong with sure.
`sw --self-upgrade`

**Comment by wisexie** [comment]
I use this day's version 22-Apr-2020 12:48

**Comment by egorpugin** [comment]
Can you post full log?

**Comment by wisexie** [comment]
Where is the log, please tell me, I did not find useful information

**Comment by egorpugin** [comment]
Just full console output you get.

**Comment by wisexie** [comment]
cmake ..
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.18363.
-- sw: processing dependencies
[174/187] [config pch]
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:631, function execute1: When executing: [config pch]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\utility(528): error C2338: tuple index out of bounds
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\utility(493): note: 参见对正在编译的 类 模板 实例化 "std::tuple_element<0,_Tuple>" 的引用
        with
        [
            _Tuple=std::tuple<>
        ]
c:\users\wise\.sw\storage\pkg\62\bd\e90f\src\sdir\src\sw\driver\target\base.h(122): note: 参见对正在编译的 别名 模板 实例化 "tuple_element_t<0,std::tuple<>>"  的引用
c:\users\wise\.sw\storage\pkg\62\bd\e90f\src\sdir\src\sw\driver\target\base.h(139): note: 参见对正在编译的函数 模板 实例化“T &sw::TargetBase::add<T,>(const sw::PackagePath &)”的引用
        with
        [
            T=sw::DirectoryTarget
        ]
c:\users\wise\.sw\storage\pkg\62\bd\e90f\src\sdir\src\sw\driver\target\base.h(191): note: 参见对正在编译的函数 模板 实例化“T &sw::TargetBase::addTarget<sw::DirectoryTarget,const sw::PackagePath&>(const sw::PackagePath &)”的引用
        with
        [
            T=sw::DirectoryTarget
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\filesystem(2447): note: 参见对正在编译的 类 模板 实例化 "std::chrono::time_point<std::filesystem::_File_time_clock,std::filesystem::_File_time_clock::duration>" 的引用
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\type_traits(520): note: 参见对正在编译的 类 模板 实例化 "std::basic_string_view<wchar_t,std::char_traits<wchar_t>>" 的引用
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\type_traits(1358): note: 参见对正在编译的 类 模板 实例化 "std::is_convertible<const _StringViewIsh &,std::basic_string_view<wchar_t,std::char_traits<wchar_t>>>" 的引用
        with
        [
            _StringViewIsh=const wchar_t *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\type_traits(1364): note: 参见对正在编译的 类 模板 实例化 "std::conjunction<std::is_convertible<const _StringViewIsh &,std::basic_string_view<wchar_t,std::char_traits<wchar_t>>>,std::negation<std::is_convertible<const _StringViewIsh &,const _Elem *>>>" 的引用
        with
        [
            _StringViewIsh=const wchar_t *,
            _Elem=wchar_t
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\xstring(2105): note: 查看指向正在编译的变量模板“const bool conjunction_v<std::is_convertible<wchar_t const * const &,std::basic_string_view<wchar_t,std::char_traits<wchar_t> > >,std::negation<std::is_convertible<wchar_t const * const &,wchar_t const *> > >”的引用
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\xstring(2264): note: 参见对正在编译的 别名 模板 实例化 "_Is_string_view_ish<const wchar_t*>" 的引用
command failed: exit code = 2
sw command: C:/Soft/sw-master-windows-client/sw.exe -static -platform x86 -compiler msvc-19.14 -d C:/Learning/tesseract/1.79.0/leptonica-1.79.0/build/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps C:/Learning/tesseract/1.79.0/leptonica-1.79.0/build/.sw/cmake/sw.txt -cmake-file-version 4
CMake Error at C:/Users/wise/.sw/storage/etc/sw/static/SWConfig.cmake:227 (message):
  sw: non-zero exit code: 1
Call Stack (most recent call first):
  CMakeLists.txt:120 (sw_execute)


-- Configuring incomplete, errors occurred!
See also "C:/Learning/tesseract/1.79.0/leptonica-1.79.0/build/CMakeFiles/CMakeOutput.log".

**Comment by egorpugin** [comment]
I see. You need newer VS. Preferable the latest - VS2019 with all updates.

**Comment by wisexie** [comment]
Thanks, i try

**Comment by wisexie** [comment]
I updated to the last version of vs2017, it is working, thank you very much
