### ISSUE TITLE
sw build Error

### ISSUE THREAD

**Issue by wisexie** [SoftwareNetwork/sw#36]
**Describe the bug**
The following error occurs when I execute sw build, but I don’t know what is ABI (16), 
can you help me see?

**Expected behavior**

sw build
[177/177] C:/Learning/tesseract/tesseract/.sw/cfg/582484/loc.sw.self.e99187-0.0.16.dll
Exception in file D:/dev/cppan2/client2/src/sw/driver/module.cpp:91, function Module: Bad config ABI version. Module ABI (17) is greater than binary ABI (16). Update your sw binary. Will rebuild on the next run.

**To Reproduce**
1. sw build 

**Information:**
 - 2010/4/22 version
 - OS Win10

**Comment by egorpugin** [comment]
`sw --self-upgrade` and try again.
You have old sw client.

**Comment by egorpugin** [comment]
Error says about it:
```Module ABI (17) is greater than binary ABI (16). Update your sw binary. ```

**Comment by wisexie** [comment]
it works very well，Thank you very much
