### ISSUE TITLE
how to build tesseract staticly using SW

### ISSUE THREAD

**Issue by goodtogood** [SoftwareNetwork/sw#37]
win10 vs2019

Is it possible to built tesseract with static link?
currently there's lots dll after compilation.
thx

**Comment by egorpugin** [comment]
Do you build tess repo or link tess with your app?
Need more info on this.

**Comment by goodtogood** [comment]
thanks for you reply.
actually I want to build libtesseract and tesseract.exe  with static link.
that's just one tesseract50.dll or tesseract.exe after compilation,
no more "org.sw.demo.danbloomberg.leptonica-1.80.0.dll" or othere dlls are need.

**Comment by egorpugin** [comment]
Try `sw -static build`

**Comment by goodtogood** [comment]
thanks.
