### ISSUE TITLE
Is there SW client uninstall facility for Windows?

### ISSUE THREAD

**Issue by x5250** [SoftwareNetwork/sw#38]
Hello!
Is there any type of removal facility to delete everything created in the file system and clean all registry entries created by SWClient?
There is also a note about building for Windows on http://www.leptonica.org/source/README.html:
"3. Run once to perform cmake integration:  sw setup".
What is this integration and can it be reverted?
Thank you.

**Comment by egorpugin** [comment]
Hi,

> removal facility to delete everything created in the file system

At the moment there is no such option, but it's pretty simple to add.

> clean all registry entries created by SWClient

Also not yet implemented.

> What is this integration and can it be reverted?

Everything is in this file:
https://github.com/SoftwareNetwork/sw/blob/master/src/sw/client/common/command/setup.cpp

---

I'll implement all cleanup cases.

**Comment by egorpugin** [comment]
Should be fixed now. Changes will be available with the next client update.
