### ISSUE TITLE
SW Setup Exception 

### ISSUE THREAD

**Issue by rweldin** [SoftwareNetwork/sw#40]
When running sw setup as an administrator I receive the error below.

R:\>sw setup
Exception in file D:/dev/primitives/src/http/src/http.cpp:248, function download_file: url = https://software-network.org/static/specification.json, curl error: SSL peer certificate or SSH remote key was not OK

**Information:**
R:\>sw --version
sw.client.sw version 1.0.0
git revision 3c3b0a7954515cc84f3903976f306292d377b377 plus 2 modified files
assembled on
15.05.2020 00:31:02 UTC
14.05.2020 19:31:02 Central Daylight Time

Windows 10 x64

**Comment by egorpugin** [comment]
Thank you! Fix will be available with the next client update.

**Comment by egorpugin** [comment]
Try it now after `sw --self-upgrade`.

**Comment by rweldin** [comment]
Everything looks good. Thank you!
