### ISSUE TITLE
sw: non-zero exit code: Exit code 0xc0000409

### ISSUE THREAD

**Issue by AlexandeRSaxoN7** [SoftwareNetwork/sw#41]
I'm trying to generate sln for https://github.com/tesseract-ocr/tesseract
Command line: cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release
Full log: https://pastebin.com/nHs4EDb8

sw command: D:/sw-client/sw.exe -shared -platform x86 -compiler msvc-19.25 -d C:/Users/AlexandeR/Desktop/tesseract-master/Win32/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps C:/Users/AlexandeR/Desktop/tesseract-master/Win32/.sw/cmake/sw.txt -cmake-file-version 4
CMake Error at C:/Users/AlexandeR/.sw/storage/etc/sw/static/SWConfig.cmake:227 (message):
  sw: non-zero exit code: Exit code 0xc0000409

Call Stack (most recent call first):
  CMakeLists.txt:219 (sw_execute)

-- Configuring incomplete, errors occurred!
See also "C:/Users/AlexandeR/Desktop/tesseract-master/Win32/CMakeFiles/CMakeOutput.log".

**Comment by egorpugin** [comment]
Can you try `sw --self-upgrade` and try it with new binary?

**Comment by AlexandeRSaxoN7** [comment]
The result is same

C:\Users\AlexandeR\Desktop\tesseract-master\Win32>sw --version
sw.client.sw version 1.0.0
git revision 37cfa3b21de687365b166d75d7838bbc1f7005ce plus 3 modified files
assembled on
17.05.2020 16:22:03 UTC
17.05.2020 19:22:03 Oeieyiaey (eaoi)

**Comment by egorpugin** [comment]
What it your OS version?

**Comment by AlexandeRSaxoN7** [comment]
Windows 10 x64 1909 (build 18363.836)

**Comment by AlexandeRSaxoN7** [comment]
Log with -trace param
https://pastebin.com/YtHQFNAC

**Comment by egorpugin** [comment]
Can you check memory usage?
How much memory do you have? Maybe sw goes out of memory?

**Comment by AlexandeRSaxoN7** [comment]
I have 16GB ram. memory usage about 4gb

**Comment by egorpugin** [comment]
No ideas at the moment. I'll think.

**Comment by egorpugin** [comment]
Please, try following:

Run `sw --self-upgrade`.

Run failing command taken from cmake error (like `D:/sw-client/sw.exe -shared -platform x86 -compiler msvc-19.25 -d C:/Users/AlexandeR/Desktop/tesseract-master/Win32/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps C:/Users/AlexandeR/Desktop/tesseract-master/Win32/.sw/cmake/sw.txt -cmake-file-version 4`) with first argument `-internal-with-crash-server=0`.

So, the command became `D:/sw-client/sw.exe -internal-with-crash-server=0 -shared -platform x86 -compiler msvc-19.25 -d C:/Users/AlexandeR/Desktop/tesseract-master/Win32/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps C:/Users/AlexandeR/Desktop/tesseract-master/Win32/.sw/cmake/sw.txt -cmake-file-version 4`.

It will write (hopefully) crash dump into c:\...\temp\ dir.
Post that crash dump here.

**Comment by AlexandeRSaxoN7** [comment]
sw folder was created in temp directory but without crash dump

**Comment by AlexandeRSaxoN7** [comment]
Two months ago I already used sw to build tesseract and all worked. Yesterday I'm tried to build tesseract again, but "sw setup" failed due to ssh error. I updated sw with sw --self-upgrade and thereafter build always failed with 0xc00000409

**Comment by egorpugin** [comment]
> "sw setup" failed due to ssl error

This was fixed.

**Comment by AlexandeRSaxoN7** [comment]
> This was fixed.
I know. I mean, there was no 0xc0000409 error before updating

**Comment by egorpugin** [comment]
When you see the error, does windows suggest to report a problem? If yes, I think you can create dump via task manager.

**Comment by AlexandeRSaxoN7** [comment]
> does windows suggest to report a problem?

No

**Comment by egorpugin** [comment]
Try with `-sd` arg:
`D:/sw-client/sw.exe -internal-with-crash-server=0 -shared -platform x86 -compiler msvc-19.25 -d C:/Users/AlexandeR/Desktop/tesseract-master/Win32/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps C:/Users/AlexandeR/Desktop/tesseract-master/Win32/.sw/cmake/sw.txt -cmake-file-version 4 -sd`

I've updated sw packages, maybe there is abi mismatch somewhere.

**Comment by AlexandeRSaxoN7** [comment]
Not working. Dump wasn't created

**Comment by egorpugin** [comment]
Is it possible to check the issue via teamviewer or chrome remote desktop?

Or you can try to run sw command with `-sleep 10` argument, in VS attach to process and then when issue occurs, VS will show call stack.

**Comment by AlexandeRSaxoN7** [comment]
![image](https://user-images.githubusercontent.com/64085106/82215206-afc23e00-991f-11ea-95db-ac16e809cb54.png)

**Comment by egorpugin** [comment]
Yes, and exacylt in this moment you can try to record dump in task mgr.

Or...
Download symbols (.pdb): https://www.dropbox.com/s/yqody5qgkdj7bn2/sw.client.sw-1.0.0.pdb.7z?dl=1

Rename sw.exe to sw.client.sw-1.0.0.exe, place that pdf near exe, re-run those steps. VS will show now normal function names.

**Comment by AlexandeRSaxoN7** [comment]
PDB that your gave doesn't match git revision 60f434f033563e4c81c61ec1462d62c6b8e00afc

**Comment by AlexandeRSaxoN7** [comment]
https://www.dropbox.com/s/8gdbhk9fh8ss7ou/sw.client.sw-1.0.0.DMP?dl=0

**Comment by egorpugin** [comment]
Thank you! Try this fixed binary.
https://www.dropbox.com/s/v87ee3d5csev1bp/sw.client.sw-1.0.0.exe.7z?dl=1

**Comment by AlexandeRSaxoN7** [comment]
Same, wait 5 minutes, i will upload dump

**Comment by AlexandeRSaxoN7** [comment]
unhandled exception at 0x00007FF86767DB9E
https://www.dropbox.com/s/qyt1pkcc2t6enol/sw.DMP?dl=0

**Comment by egorpugin** [comment]
Ok, the problem is clear now.
Cl.exe prints russian characters (non-utf8), and they are tried to be saved into json in dtor. Json throws an error then.
I'll ping when it is fixed.

**Comment by egorpugin** [comment]
Try this one https://www.dropbox.com/s/tyclsld5wn0hgnf/sw.client.sw-1.0.0.exe.7z?dl=1

**Comment by AlexandeRSaxoN7** [comment]
0xc0000409
https://pastebin.com/4FJdLxhw

**Comment by egorpugin** [comment]
Ok, fixing further...

**Comment by egorpugin** [comment]
This one?
https://www.dropbox.com/s/3vrlq9qiifjlwrz/sw.client.sw-1.0.0.exe.7z?dl=1

**Comment by AlexandeRSaxoN7** [comment]
Seems like its working.

**Comment by charmainewee** [comment]
Hi, 

I'm facing the same problem except I'm trying to build Leptonica (the Tesseract dependency). Could you upload/send the fixed binary again so I can try it? The dropbox link returns a 404 error. 

Thank you!

**Comment by egorpugin** [comment]
Done. Use `sw --self-upgrade`.

**Comment by JohnnyLeung996** [comment]
Hi! I face a similar issue:
sw command: H:/Tools/Software Network/sw.exe -static -platform x64 -compiler msvc-19.29 -d D:/tesseract-main/build/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps D:/tesseract-main/build/.sw/cmake/sw.txt -cmake-file-version 9
CMake Error at C:/Users/Johnny/.sw/storage/etc/sw/static/SWConfig.cmake:267 (message):
  sw: non-zero exit code: 1
Call Stack (most recent call first):
  CMakeLists.txt:399 (sw_execute)

How can I fix it?

**Comment by egorpugin** [comment]
Hi, please post logs (output).
Use cmake flag when configuring `-DSW_DEBUG=1`
