### ISSUE TITLE
compile tesseract

### ISSUE THREAD

**Issue by ghost** [SoftwareNetwork/sw#43]
I'm generating tesseract sln with 
> cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release

but when i'm compiling release x86 i'm get link error what .lib not exists
![image](https://user-images.githubusercontent.com/64085106/82237570-88c73480-993e-11ea-83dd-3760440d370a.png)

**Comment by egorpugin** [comment]
I try on clear storage. Works fine.
```
cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release
cmake --build .
```

Can you describe your steps more deeply?
Like:
1) You ran that command.
2) Opened VS
3) Press build?

**Comment by AlexandeRSaxoN7** [comment]
1. Removed .sw folder
2. Ran sw setup
3. Ran that command.
4. Opened VS
5. Press build

If I'm building with cmake --build . then I got new link erros. Full log here: https://pastebin.com/PaMEAP2x

**Comment by egorpugin** [comment]
> new link erros

That's ok, someone broke tess cmake build.

> I get several thousand warnings, is this normal?

That's ok too. For some reason noone wants to fix them.

**Comment by AlexandeRSaxoN7** [comment]
> That's ok, someone broke tess cmake build.
What am I supposed to do?

**Comment by egorpugin** [comment]
I've opened an issue.
https://github.com/tesseract-ocr/tesseract/issues/2986

**Comment by egorpugin** [comment]
> 1. Removed .sw folder
> 2. Ran sw setup
> 3. Ran that command.
> 4. Opened VS
> 5. Press build
> 
> If I'm building with cmake --build . then I got new link erros. Log here: https://pastebin.com/PaMEAP2x
> 
> Also during the compilation process I get several thousand warnings, is this normal?

Tried this, I see only link error.

**Comment by AlexandeRSaxoN7** [comment]
And what to do with org.sw.fribidi.fribidi-1.0.9.lib

**Comment by egorpugin** [comment]
I forget to set release build. Now I see it too. I'll investigate.

**Comment by egorpugin** [comment]
Try this binary:
https://www.dropbox.com/s/pw1p31j0t5go0n8/sw.client.sw-1.0.0.exe.7z?dl=1

Also @rweldin can you check please if double link libraries are gone?

**Comment by rweldin** [comment]
Egor, I'll check tonight after work and will get back to you. Likely won't
be able to test for another 8-10 hours. Thanks!

**Comment by AlexandeRSaxoN7** [comment]
> Try this binary:
> https://www.dropbox.com/s/pw1p31j0t5go0n8/sw.client.sw-1.0.0.exe.7z?dl=1
> 
> Also @rweldin can you check please if double link libraries are gone?

Its working, but one error left
![image](https://user-images.githubusercontent.com/64085106/82352458-afe93900-9a06-11ea-9d1e-45bcb10e5173.png)

**Comment by egorpugin** [comment]
Can you show Output tab?

**Comment by AlexandeRSaxoN7** [comment]
Sorry, all fine. But when i'm running any of compiled exe then i got error 0xc000007b

**Comment by egorpugin** [comment]
Try to clear build dir and try again. I think it is related to shared build and you have old dlls or something like this.

**Comment by AlexandeRSaxoN7** [comment]
Removed .sw folder
Ran sw setup
Ran cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build
Opened VS, selected release x86
Pressed build
got 0xc000007 after executing

**Comment by AlexandeRSaxoN7** [comment]
Solved.

**Comment by egorpugin** [comment]
What was that?

**Comment by AlexandeRSaxoN7** [comment]
I dont know. I just added -DSTATIC=1 for generate solution. But now another bug has appeared only when compiling text2image and idk why. Maybe its a sw or tesseract bug https://pastebin.com/PYA37bpT
if I set /SAFESEH:NO then everything is fine.

**Comment by egorpugin** [comment]
0xc000007b confirmed.
SAFESEH confirmed.

**Comment by rweldin** [comment]
Confirmed the build in this email chain did remove the duplicate entries in
the Linker > Additional Dependencies section of Visual Studio.

I attempted to build and received the error below:

3>Auto build dll exports
3>LINK : fatal error LNK1181: cannot open input file
'C:\.sw\storage\pkg\75\6a\600e\obj\bld\657802\lib\org.sw.demo.danbloomberg.leptonica-1.80.0.lib'
3>Done building project "libtesseract.vcxproj" -- FAILED.
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I was not able to locate the org.sw.demo.danbloomberg.leptonica-1.80.0.lib
file on my computer. If you need anything else let me know. Thanks!

**Comment by egorpugin** [comment]
Let's keep the issue open for a while.

**Comment by kuzmenko-andrey** [comment]
I've tried to build tesseract from lasted sources. I've removed all files from C:\Users\user\.sw and use the next commands for checkout and build
`sw setup
git clone https://github.com/tesseract-ocr/tesseract tesseract
cd tesseract
mkdir build && cd build
cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=inst`

Then open the VS solution and build it. As a result, when I'm running tesseract.exe I've got an error
![image](https://user-images.githubusercontent.com/61830814/98388008-d35a7b80-205a-11eb-8703-55e194ac7922.png)

Have you any solution to fix this problem?

**Comment by egorpugin** [comment]
Try `sw --self-upgrade`. Post `sw --version`.
I thought this was fixed. I'll check locally too.

**Comment by egorpugin** [comment]
Confirmed.

**Comment by egorpugin** [comment]
I've tracked the issue, need to think about better solution.

> Have you any solution to fix this problem?

You can try to remove `org.sw.demo.xz_utils.lzma-5.2.4.dll` file and run cmake build again. There is a race between copying x86 and x64 files into output dir. So, after 1-2 retries, you should get proper binary.
Or copy it yourself from `sw storage path\pkg\2a\68\57cb\obj\bld\x86 config dir here` (check cfg.json inside last dir to find corresponding dll - x86 debug or release).

Sorry for such silly workdaround.

**Comment by kuzmenko-andrey** [comment]
Thanks, for your help
