### ISSUE TITLE
compile leptonica

### ISSUE THREAD

**Issue by AlexandeRSaxoN7** [SoftwareNetwork/sw#44]
How to build static leptonica .lib which will no require other .libs or .dlls? If i build with sw build -static -platform Win32 then I got link errors after compiling in my project
![image](https://user-images.githubusercontent.com/64085106/82479334-e55f5680-9ada-11ea-90d4-7739b56e948f.png)

**Comment by AlexandeRSaxoN7** [comment]
If I build with sw build -static -platform Win32 -win-mt then I got only this errors
![image](https://user-images.githubusercontent.com/64085106/82480203-2146eb80-9adc-11ea-9f98-f7490e530f14.png)

**Comment by egorpugin** [comment]
Try to add `-static-dependencies`.

**Comment by AlexandeRSaxoN7** [comment]
> Try to add `-static-dependencies`.

.lib does not build

**Comment by egorpugin** [comment]
> How to build static leptonica .lib which will no require other .libs or .dlls?

Oh, I see. Seems you need something like this
https://stackoverflow.com/questions/13492365/how-to-merge-two-windows-vc-static-library-into-one

There's no such function in sw yet.

**Comment by egorpugin** [comment]
And I'm not sure if any build system gives you to do this.

**Comment by AlexandeRSaxoN7** [comment]
Okay. I included to my project all .libs which leptonica needs but i cannot find jp2kio

![image](https://user-images.githubusercontent.com/64085106/82489602-9c170300-9aea-11ea-9bd6-a6f684835c3e.png)

**Comment by egorpugin** [comment]
Did you check https://software-network.org/org.sw.demo.danbloomberg.leptonica/dependencies ?

**Comment by AlexandeRSaxoN7** [comment]
Yes. Seems like its jp2kio.c from leptonica source code but i dont know how to include it to my project

**Comment by egorpugin** [comment]
What symbol is missing? You cut them.

**Comment by egorpugin** [comment]
opj is openjpeg library.
https://software-network.org/org.sw.demo.uclouvain.openjpeg.openjp2

**Comment by AlexandeRSaxoN7** [comment]
Yes, thanks!
