### ISSUE TITLE
sw setup: cannot close database

### ISSUE THREAD

**Issue by tomJa99** [SoftwareNetwork/sw#45]
**Describe the bug**
I have troubles setting up software network on my computer. I downloaded the binary and ran 
`sw setup`

This produced the following error message:
```
Sqlite3 error: Can't close database: unable to close due to unfinalized statements or unfinished backups
Exception in file D:/dev/cppan2/client2/src/sw/manager/storage_remote.cpp:285, function load: sqlite3_step() failed: NOT NULL constraint failed: package_version.archive_version
```

Do I have to configure something to solve this issue or is this an actual bug?

I am currently working on a Windows 10 OS and I need sw to build leptonica and tesseract.

**Comment by egorpugin** [comment]
Try to remove sw database. It will be re-created again.
Remove `C:\Users\u\.sw\storage\etc\sw\database` dir or if you changed storage dir, go to it and remove `etc\sw\database` dir.

**Comment by tomJa99** [comment]
I removed the folder but I still get the same error
