### ISSUE TITLE
No ca certs file was found for GRPC

### ISSUE THREAD

**Issue by hero106wen** [SoftwareNetwork/sw#48]
An error throws out when I use sw on windows, Do I need to install a cert? How?

GrpcChannel Remote::getGrpcChannel() const
{
    // keeping channel for too long causes issues
    // so we create a new one every time

    static std::mutex m;
    std::unique_lock lk(m);

    static const grpc::SslCredentialsOptions ssl_options = []()
    {
        grpc::SslCredentialsOptions ssl_options;
        path certsfn;
        // system's certs first?
        if (auto f = primitives::http::getCaCertificatesBundleFileName())
            certsfn = *f;
        else
        {
            certsfn = support::get_ca_certs_filename();
            if (!fs::exists(certsfn))
                throw SW_RUNTIME_ERROR("No ca certs file was found for GRPC.");
        }
        ssl_options.pem_root_certs = read_file(certsfn);
        return ssl_options;
    }();

    auto creds = grpc::SslCredentials(ssl_options);
    auto channel = grpc::CreateChannel(api_url, secure ? creds : grpc::InsecureChannelCredentials());
    return channel;
}

**Comment by egorpugin** [comment]
Hi,

1. What is your `sw --version` output?
2. Try to remove `c:\Users\u\.sw\certs\` dir and try again.

**Comment by egorpugin** [comment]
Try sw --self-upgrade and re-run again.
