### ISSUE TITLE
Recent egorpugin/primitives commits break SW

### ISSUE THREAD

**Issue by ollydev** [SoftwareNetwork/sw#50]
Using SW to build Tesseract-OCR, it's great! However the recent changes on `egorpugin/primitives` completely break SW.

https://github.com/ollydev/tesseract/runs/1087514185?check_suite_focus=true#step:4:489

Should a working `egorpugin/primitives` version be used rather than the master branch?

**Comment by egorpugin** [comment]
Hi,

Sorry for that!

I'm upgrading SW to C++20 (formally, only compiler flag for now). And it caused that.
Working on a fix. Win/macos fix is done, linux is underway.

**Comment by egorpugin** [comment]
Try `sw --self-upgrage` and then your usual commands.

**Comment by ollydev** [comment]
Thanks, Windows and Linux are working!
I see you're currrently tackling `error: invalid value 'c++20' in '-std=c++20'` on macOS.

**Comment by egorpugin** [comment]
Yep, trying to fix.
This is because appleclang has different version scheme, so sw can't select c++20 flag correctly.

**Comment by egorpugin** [comment]
Ok, should be fine now. Everything is green in total.
