### ISSUE TITLE
I don't know how to add package that build by SW to my project.

### ISSUE THREAD

**Issue by z-pc** [SoftwareNetwork/sw#54]
First, I'm sorry if this is spam or silly.  This is a first I use SW, and I don't have much time left for my project.

I'm trying build tesseract library to add to my project.
My command line:
`sw setup`
`sw build org.sw.demo.google.tesseract.tesseract-maste`

It's done. But I don't know, where is the library, header file to add to my project.
Or am I mistaking something?
Thanks your support.

**Comment by egorpugin** [comment]
How do you build your project? Using cmake or just VS project (solution)?

**Comment by z-pc** [comment]
I use CMake and VS to build library 3rdParty.
and just VS2015 with my project.
I build SW by VS2019.

OS: Win10

**Comment by egorpugin** [comment]
See this cmake integration example of how to use SW deps in your cmake project.
https://github.com/SoftwareNetwork/sw/blob/master/test/integrations/cmake/tess/CMakeLists.txt#L7

**Comment by z-pc** [comment]
Thanks for help and your time.

**Comment by egorpugin** [comment]
If you want to gather all deps, includes, compiled libraries, it's not possble at the moment (you can do it manually, but it does not worth it), because sw is intended to be used as build system or integrated as package manager with some other build system.

**Comment by z-pc** [comment]
Yep...
I was looking for tesseract in C:\\User\ABC\.sw\storage, it is very difficult to gather them.
At the moment, I do not have the resources for integrated both CMake and SW into my project. It seems that it should be used at the beginning. I will try to find another way.
Thanks for all.

**Comment by egorpugin** [comment]
In other words if sw is able to integrate deps into your VS project directly, it would be fine for you?
(I consider such VS integration.)

**Comment by z-pc** [comment]
I guess so. In fact, I don't fully understand SW.

**Comment by z-pc** [comment]
If you don't mind, I'm having a little bit of trouble building tesseract x86, [here](https://github.com/tesseract-ocr/tesseract/issues/3067)
It seems to be related to SW.

**Comment by egorpugin** [comment]
> In fact, I don't fully understand SW.

Sw is a build system (like cmake and can be used instead) and a package manager (like conan/vcpkg).
It also can work in PM mode only (during cmake integration).

> It seems to be related to SW.

Yes, I'll try to investigate.

**Comment by egorpugin** [comment]
Can you send me more info about that issue?
Delete `C:/Users/ABC/.sw/storage/etc/sw/checks/` directory.
Run again and send log of this command:
`sw.exe -trace -shared -platform x86 -compiler msvc-19.0 -d E:/Project/tesseract/tesseract/build/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps E:/Project/tesseract/tesseract/build/.sw/cmake/sw.txt -cmake-file-version 4`

**Comment by z-pc** [comment]
I installed both VS 2019 and 2015, build SW with VS2019, and I want to target tesseract with VS2015.

Before that, I generate tesseract x64 successfully. with command:
`cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=inst`
compile is okey.

Then I generate x86, with command:
`cmake .. -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=inst`
Its error.

This is trace after delete checks dir:
[tracelog.txt](https://github.com/SoftwareNetwork/sw/files/5274831/tracelog.txt)

More info:
List of detected programs:
Microsoft Visual Studio C/C++ Compiler (short form - msvc):
release:
- 19.0.24210 (x86_64, x86, arm)
- 19.27.29111 (x86_64, x86)
sw.client.sw version 1.0.0
git revision 0275778ff64dd050fc9d25cec21d13617a44dc1c
assembled on
17.09.2020 23:47:21 UTC
18.09.2020 06:47:21 SE Asia Standard Time

**Comment by z-pc** [comment]
Sorry, I just tried to run again.
1. Run command
`cmake .. -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=inst`
>> [genlog.txt](https://github.com/SoftwareNetwork/sw/files/5275096/genlog.txt)
2. Run trace:
`sw.exe -trace -shared -platform x86 -compiler msvc-19.0 -d E:/Project/tesseract/tesseract/build86/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps E:/Project/tesseract/tesseract/build86/.sw/cmake/sw.txt -cmake-file-version 4`
>> it's show log (shorter)  
[tracelog.txt](https://github.com/SoftwareNetwork/sw/files/5275104/tracelog.txt)
3. Delete check dir, and run trace again:
>>longer,  I am copy only the last some thousand lines
 [tracelog2.txt](https://github.com/SoftwareNetwork/sw/files/5275126/tracelog2.txt)

Hope you see a clue

**Comment by egorpugin** [comment]
Yes, I see a problem. I'll prepare a fix and send you new binary to test it.

**Comment by egorpugin** [comment]
Can you check `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib` path - do you have `oldnames.lib` in it?

Now run again:
Delete `C:/Users/ABC/.sw/storage/etc/sw/checks/` directory.
Run again and send log of this command:
`sw.exe -trace -shared -platform x86 -compiler msvc-19.0 -d E:/Project/tesseract/tesseract/build/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps E:/Project/tesseract/tesseract/build/.sw/cmake/sw.txt -cmake-file-version 4 2> trace.log`

I've added ` 2> trace.log` to the end of sw call. Because your logs contain only end of log and no beginning.

**Comment by egorpugin** [comment]
Ok, I've fixed the issue.
Run `sw --self-upgrade`, usual cmake commands then.

**Comment by z-pc** [comment]
Sorry for the late response.
I did:
1. Delete check dir
2. Run `sw --self-upgrade` 
3. Run `cmake .. -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=inst` > still error
4. Run trace: 
[trace.log](https://github.com/SoftwareNetwork/sw/files/5280291/trace.log)

**Comment by egorpugin** [comment]
Ah, you still need to delete `C:/Users/ABC/.sw/storage/etc/sw/checks/` directory.

**Comment by z-pc** [comment]
>Can you check C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib path - do you have oldnames.lib in it?
Yes, its exist

I delete check dir, and run trace again.
[trace.log](https://github.com/SoftwareNetwork/sw/files/5281939/trace.log)

**Comment by egorpugin** [comment]
Check `sw --version`, try `sw setup` again.

**Comment by z-pc** [comment]
> Check sw --version
sw.client.sw version 1.0.0
git revision aec3e13abb9e1efd1a30e72dbf1e7feedcc74eb8
assembled on
24.09.2020 14:20:48 UTC
24.09.2020 21:20:48 SE Asia Standard Time
>  try sw setup again
I did, still error.
Will I use VS 2019 to build SW, and the VS2015 compiler for build tesseract is the cause?

**Comment by egorpugin** [comment]
Please, do it again:

Delete `C:/Users/ABC/.sw/storage/etc/sw/checks/` directory.
Run again and send log of this command (`trace.log`):
`sw.exe -trace -shared -platform x86 -compiler msvc-19.0 -d E:/Project/tesseract/tesseract/build/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps E:/Project/tesseract/tesseract/build/.sw/cmake/sw.txt -cmake-file-version 4 2> trace.log`

**Comment by z-pc** [comment]
I did: 
[trace.log](https://github.com/SoftwareNetwork/sw/files/5282116/trace.log)

**Comment by egorpugin** [comment]
I've made small change and uploaded new binaries.
Run `sw --self-upgrade`, delete checks dir again, re-run long command and send `trace.log`.
Sorry for such burden, I'm trying to understand what's different on your system. (Locally your case works for me.)

**Comment by z-pc** [comment]
I'm very grateful for your help.
This is trace log. 
[trace.log](https://github.com/SoftwareNetwork/sw/files/5282224/trace.log)

I will try creating machine virtual, and try build on it.
Sorry for the response too late, because I was put on limited a upload file permissions and available on my system.

**Comment by egorpugin** [comment]
Ok, do the same one more time.
Upgrade, delete checks, run command.
I've made another fix.

**Comment by z-pc** [comment]
I have upgraded sw, delete checks, and tried run 
`cmake .. -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=inst`
It's worked, and generate successfully solution.

Next I run:
` cmake --build . --config Release --target install`
It's error, this is a log.
[build.log](https://github.com/SoftwareNetwork/sw/files/5286214/build.log)
And this is a log when I try build again in VS2015 IDE, 
"'gobject/glib-enumtypes.h': No such file or directory"
[buildbyvs.log](https://github.com/SoftwareNetwork/sw/files/5286216/buildbyvs.log)

I search "glib-enumtypes.h" in \User\ABC\.sw\ , not exist, but I see "glib-enumtypes.h.template" and "glib-enumtypes.c.template" in "C:\Users\ABC\\.sw\storage\pkg\ef\91\56e5\src\sdir\gobject"

Finally, I delete check dir again, and run trace log, it's seem a log is not fully.
[trace.log](https://github.com/SoftwareNetwork/sw/files/5286219/trace.log)
I'm not sure if this issue belongs to sw?

**Comment by egorpugin** [comment]
I see. Previous issue is fixed now. This is a new one.
I'll investigate.

**Comment by egorpugin** [comment]
Run `sw --self-upgrade` and try again.

**Comment by z-pc** [comment]
It's worked, build successfully on both x86 and x64.
Thanks you so much, Egor Pugin, you are awesome.

**Comment by egorpugin** [comment]
Thank you for reports!
