### ISSUE TITLE
Link "FAQ" at software-network.org gets me error 404 not found

### ISSUE THREAD

**Issue by hartwork** [SoftwareNetwork/sw#55]
Hi!

When I browse to https://software-network.org/ and click link "F.A.Q." that points to https://github.com/SoftwareNetwork/sw/blob/master/doc/faq.md I get error 404 not found. Is that known? Where can I find the FAQ now?

Best, Sebastian

**Comment by egorpugin** [comment]
Hi,

Please refer to the documentation https://software-network.org/client/sw.pdf
It has migrated FAQ, but there are no much questions.

**Comment by hartwork** [comment]
I see, thanks. Can the dead `F.A.Q.` link be dropped from the homepage then? Thank you!

**Comment by egorpugin** [comment]
Done.
