### ISSUE TITLE
Cannot build on VS2017

### ISSUE THREAD

**Issue by stamy0** [SoftwareNetwork/sw#58]
Hi,

we are using Tesseract in production and we are building it with SW.
We are using the VS2017 compiler (we cannot update yet) and had success building Tesseract that way.
However I have found out that recently you have added CPP17 features (if I recall correctly, it is std::optional that is causing problems) to SW and that makes it impossible to build the new master branch of Tesseract.
My question is that is it still possible to build SW projects using older compilers such as VS2017?

Thanks in advance.

**Comment by egorpugin** [comment]
Hi,

> My question is that is it still possible to build SW projects using older compilers such as VS2017?

Yes, it is possible. SW can build software for any compiler version.
The thing is that you need to install VS2019 near VS2017 or other compiler.
VS2019 is used by sw to build its scripts which are in C++17-20 already, and you continue to use VS2017 for tess.

VS2019 community is free for such use, but I assume you cannot upgrade still.
Is it possible to install VS2019 build tools - a lightweight distribution of compilers and VS c++ libs?
If not, in this case I think I can try to implement building configs using clang-cl (which should be more acceptable as it is FOSS)...
But clang-cl will also require MS STL library which comes with VS2019/build tools.

So, if you provide more info on this, we'll think how we could overcome you issue.

**Comment by stamy0** [comment]
@egorpugin if I am able to tell SW to build the Tesseract itself with VS2017 instead of VS2019 then installing the VS2019 build tools is a reasonable solution for me.

**Comment by egorpugin** [comment]
> Note that currently I am calling SW within a VS2017 x64 Native Tools Command Prompt.

For sw it is no matter what shell is used - even mingw shell is ok

>  if I am able to tell SW to build the Tesseract itself with VS2017 instead of VS2019

Use `sw -compiler msvc-19.16 ...` to build with VS2017. Or your installed cl.exe version.
Check it with `cl /?` in VS2017 x64 Native Tools Command Prompt.

**Comment by stamy0** [comment]
Thank you @egorpugin , as soon as I can try these settings and validate that they indeed provide the result that I want I'll get back here and close this issue.

**Comment by stamy0** [comment]
I have verified that I can successfully build it the way you've suggested. Thanks you for the help.
