### ISSUE TITLE
software-network.org is unreachable

### ISSUE THREAD

**Issue by stamy0** [SoftwareNetwork/sw#59]
software-network.org is unreachable and any attempt to build with sw fails with the following error:
`Exception in file D:/dev/swst/pkg/dd/cf/960d/src/sdir/src/http/src/http.cpp:258, function download_file: url = https://software-network.org/static/specification.json, curl error: Couldn't connect to server`

**Comment by egorpugin** [comment]
Hi,

Sorry for that, I'm upgrading server configuration today.

**Comment by stamy0** [comment]
Understood, I'll close this one once its back up.

**Comment by egorpugin** [comment]
Please test and report back.

Also don't close the ticket. I'll think how we can mitigate this on client side.
Probably some default built-in config in case if the website is down.
Db and packages will be still useful and downloadable from mirrors.

**Comment by stamy0** [comment]
I can confirm that it is working now. I'll keep this ticket open as you've requested.
