### ISSUE TITLE
cppan

### ISSUE THREAD

**Issue by NanaSeino233** [SoftwareNetwork/sw#60]
can't use cppan command

**Comment by egorpugin** [comment]
Hi,

The server was shut down couple of days ago after 5 years of work.
Please migrate to sw.

How do you use cppan command?
I can help with migration.

**Comment by NanaSeino233** [comment]
> 你好
> 
> 经过5年的工作，几天前服务器已关闭。
> 请迁移到sw。它是cppan v2。
> 
> 您如何使用cppan命令？
> 我可以协助迁移。

Then how can i use cppan v2?

**Comment by NanaSeino233** [comment]
> ## 有关sw的信息，请参见：[https](https://software-network.org/) : [//software-network.org/](https://software-network.org/)
> 您如何使用cppan？

I mean how can I use the cppan command to configure related dependent projects as before

**Comment by egorpugin** [comment]
How did you use it before?

**Comment by NanaSeino233** [comment]
> 您以前如何使用它？

The first is the cppan -V command. Create some folders on the C drive, switch to the leptonica directory before, and use the cppan command to download the image format dependencies such as pvt.cppan.demo.jpeg-9.2.0. 
But now I cannot use these instructions.I'm sorry that I may not be very clear.

**Comment by egorpugin** [comment]
Try `sw --help`.
Use `sw build` in leptonica directory (from master branch).

**Comment by NanaSeino233** [comment]
> Try `sw --help`.
> Use `sw build` in leptonica directory (from master branch).

I want to know what command should I use instead of cppan if I want to download dependencies in sw

**Comment by egorpugin** [comment]
Download sw client from https://software-network.org/client/
Run `sw build packagename`.
Package list is available here https://software-network.org/
Also you can run `sw list packagename`
