### ISSUE TITLE
Windows : CMake and sw can't build wxwidgets

### ISSUE THREAD

**Issue by RiwEZ** [SoftwareNetwork/sw#61]
**Describe the bug**
CMake and sw can't build wxwidgets on my project. I don't know if this is a wxwidgets problem or cmake,sw problem

**To Reproduce**
my CMakeLists.txt
```
cmake_minimum_required(VERSION 3.19)

project(main CXX)
set(CMAKE_CXX_STANDARD 17)
set(SW_BUILD_SHARED_LIBS 1)
set(DEPENDENCIES
    org.sw.demo.wxwidgets.base-3.1.4
    org.sw.demo.wxwidgets.base-3.1.4
)

find_package(SW REQUIRED)
sw_add_package(${DEPENDENCIES})
sw_execute()

include_directories(${CMAKE_CURRENT_SOURCE_DIR})

add_executable(main main.cpp)
target_link_libraries(main ${DEPENDENCIES})

```
cmake --build result and main.cpp
https://gist.github.com/RiwEZ/16dbe6bff6c4ad32d87b5b9d58d37092

**Information:**
 -  `sw --version` output.
```
sw.client.sw version 1.0.0
git revision 22757a4388a99010ffdee79011fbde5af50cee17 plus 1 modified files
assembled on
15.02.2021 19:13:29 UTC
16.02.2021 02:13:29 SE Asia Standard Time
```
- cmake version 3.19.4
 - Windows 10 64 bits

**Comment by egorpugin** [comment]
Hi,

I've made a fix, it should be available within 5-15 mins. Try to generate cmake project again or remove `.sw` dir in cmake binary dir.
I'm not familiar with wxwidgets, so if any issues remain, please report.

**Comment by egorpugin** [comment]
Also note, to use gui components, you need `wxwidgets.core` and not `wxwidgets.base` package.
```
set(DEPENDENCIES
    org.sw.demo.wxwidgets.core
)
```

**Comment by RiwEZ** [comment]
ahh I messed up, yeah one of the dependencies should be wxwidgets.core 
still got errors but does not seem to be sw problem.
```
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  sw: building dependencies
MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_m 
ain(void)" (?invoke_main@@YAHXZ) [D:\Projects\cpp\CPEPROJECT\testcmake\build\main.vcxproj]
D:\Projects\cpp\CPEPROJECT\testcmake\build\Debug\main.exe : fatal error LNK1120: 1 unresolved externals [D:\Projects\cp 
p\CPEPROJECT\testcmake\build\main.vcxproj]
```

**Comment by egorpugin** [comment]
Add `WIN32` to cmake.
`add_executable(main WIN32 main.cpp)`

**Comment by RiwEZ** [comment]
thanks a lot, It's working now
