### ISSUE TITLE
How to build a other version package, what is not available on https://software-network.org/

### ISSUE THREAD

**Issue by z-pc** [SoftwareNetwork/sw#66]
Hi @egorpugin 
I want to build older version of Tesseract (at time VS2015 was supporting, because I'm not ready for upgrade).
On https://software-network.org/, I see only master version.
Whether I can add other version, or choose exactly release version on git?
Thanks.

**Comment by egorpugin** [comment]
Hi, I can try to add version you need.
What is the number?

**Comment by z-pc** [comment]
I think "Tesseract 5.0.0-alpha-20201224" will be fine for VS2015.
Honestly, I'm not sure.

**Comment by egorpugin** [comment]
I'm not sure that they'll work.
We switched to C++17 in some last 5.0.0-alpha tags.
You need 4..0 or 4.1 probably.

**Comment by z-pc** [comment]
It's ok.
Please help me add Tesseract 4.1.
Thanks

**Comment by egorpugin** [comment]
I've uploaded 4.1.1 version.
Replace `-master` version with `-4` suffix.

**Comment by z-pc** [comment]
Thank so much @egorpugin
