### ISSUE TITLE
fatal error C1057: unexpected end of file in macro expansion

### ISSUE THREAD

**Issue by rx-ted** [SoftwareNetwork/sw#68]
`sw build -static `

.......
[1744/8207] [org.sw.demo.census.opencensus.cpp-0.4.0]/opencensus/trace/internal/attribute_value.cc
[1747/8207] [org.sw.demo.xz_utils.lzma-5.2.4]/src/liblzma/common/alone_encoder.c
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:764, function execute1: When executing: [org.sw.demo.lexxmark.winflexbison.bison-3.7.4]/bison/src/print-graph.c
C:/Users/{USER}/.sw/storage/pkg/47/49/7d9e/src/sdir/bison/src/print-graph.c(1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
C:/Users/{USER}/.sw/storage/pkg/47/49/7d9e/src/sdir/bison/src/print-graph.c(87): error C2001: newline in constant
C:/Users/{USER}/.sw/storage/pkg/47/49/7d9e/src/sdir/bison/src/print-graph.c(87): fatal error C1057: unexpected end of file in macro expansion
command failed: exit code = 2
Total errors: 1

**Why is that? How to solve it?**
I have repeated it many times, but it is the same.

**Comment by egorpugin** [comment]
What is your compiler, os?

**Comment by gjy20sui** [comment]
Windows10. I haven't installed CPPAN on my system, so I went to install it and found this problem.燃-------- 原始邮件 --------发件人： Egor Pugin ***@***.***>日期： 2021年5月17日周一 12:47收件人： SoftwareNetwork/sw ***@***.***>抄送： 燃 ***@***.***>, Author ***@***.***>主    题： Re: [SoftwareNetwork/sw] fatal error C1057: unexpected end of file in macro expansion (#68)
What is your compiler, os?

**Comment by egorpugin** [comment]
You can try to download a binary directly from https://software-network.org/client/

**Comment by gjy20sui** [comment]
OK, I'll try燃-------- 原始邮件 --------发件人： Egor Pugin ***@***.***>日期： 2021年5月17日周一 17:14收件人： SoftwareNetwork/sw ***@***.***>抄送： 燃 ***@***.***>, Author ***@***.***>主    题： Re: [SoftwareNetwork/sw] fatal error C1057: unexpected end of file in macro expansion (#68)
You can try to download a binary directly from https://software-network.org/client/
