### ISSUE TITLE
 error C2760: syntax error: unexpected token 'const', expected 'declaration'

### ISSUE THREAD

**Issue by rx-ted** [SoftwareNetwork/sw#69]
.sw\storage\pkg\4a\1e\0168\src\sdir\include\boost/context/windows/protected_fixedsize_stack.hpp(49): error C2760: syntax error: unexpected token 'const', expected 'declaration'

.sw\storage\pkg\4a\1e\0168\src\sdir\include\boost/context/windows/protected_fixedsize_stack.hpp(73): note: see reference to class template instantiation 'boost::context::basic_protected_fixedsize_stack<traitsT>' being compiled

How to solve it ?

**Comment by egorpugin** [comment]
Compiler? Os? Boost version?

**Comment by rx-ted** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
