### ISSUE TITLE
sw: non-zero exit code: 1 [CLion mingw-w64

### ISSUE THREAD

**Issue by jkoking** [SoftwareNetwork/sw#74]
**Describe the bug**
When I load my cmakelists.txt i get this error
CMake Error at C:/Users/Jacob/.sw/storage/etc/sw/static/SWConfig.cmake:235 (message):
  sw: non-zero exit code: 1
Call Stack (most recent call first):
  CMakeLists.txt:15 (sw_execute)

**Expected behavior**
Cmake to configure without failing.

**To Reproduce**
Create a cmakelists.txt
Reload cmake 

**Information:**
sw.client.sw version 1.0.0
git revision db82472ee934dfb8e064af419d4d8d4254b724a3
assembled on
02.06.2021 21:58:26 UTC
02.06.2021 17:58:26 Eastern Daylight Time
 Windows 64 bit
minGW-w64-x86_64-8.1.0-posix-seh-rt_v6-rev0
IDE CLion 2021.1.2
B	uild #CL-211.7442.42, built on June 1, 2021A
[CMakeLists.txt](https://github.com/SoftwareNetwork/sw/files/6760364/CMakeLists.txt)
[clion-log.txt](https://github.com/SoftwareNetwork/sw/files/6760366/clion-log.txt)
[CMakeOutput.log](https://github.com/SoftwareNetwork/sw/files/6760367/CMakeOutput.log)

**Comment by egorpugin** [comment]
Hi,

Mingw workflows are bugged currently.
There were multiple reports already.
These bugs will be revisited after next major update.
