### ISSUE TITLE
Command sw run throwing exception

### ISSUE THREAD

**Issue by Telokis** [SoftwareNetwork/sw#75]
**Describe the bug**
Running `sw run main.cpp` throws an exception:

```
> sw run "src/vector/vector.cpp"
Downloading database from origin remote
[1/3] [vector-0.0.1]/vector.cpp
[2/3] [vector-0.0.1]/[bdir_pvt]/sw.rc
[3/3] [vector-0.0.1].exe
Exception in file D:/dev/cppan2/client2/src/sw/client/common/command/run.cpp:132, function command_run: More than one target provided in input
```

If I run the generated file manually, it works as expected. (A simple "Hello World" main)

**Expected behavior**
After successfully building the executable, it should run it properly.

**To Reproduce**
1. Create a very simple `test.cpp` file
2. `sw run test.cpp`

**Information:**
sw.client.sw version 1.0.0
git revision db82472ee934dfb8e064af419d4d8d4254b724a3
assembled on
02.06.2021 21:58:26 UTC
02.06.2021 23:58:26 Romance Daylight Time

 - Windows 10
 - MSVC 2017

**Comment by egorpugin** [comment]
Hi,

`sw run` is not tested that much, so issues are possible.
Let's keep ticket open.
Such fixes will be implemented after some core algorithms.

**Comment by egorpugin** [comment]
Fixed in https://github.com/SoftwareNetwork/sw/commit/88086b3914a62d6b703b33167240d7cd0613ea8c
