### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by qxf5454** [SoftwareNetwork/sw#76]
I wanted to compile tesseract-ocr,and it needs a package org.sw.demo.preshing.junction-master. I've tried many times,but i cant download it.Please check what is wrong.
Using China Telecom hotspot,iphone11. other packages were successfully downloaded

<img width="361" alt="捕获" src="https://user-images.githubusercontent.com/26813723/127967587-4f9f052a-b6fc-4e5b-b525-e10253357872.PNG">

**Comment by egorpugin** [comment]
Hi,

For some reason it cannot download cert file. Probably it is banned by your provider.
It seems that I need to update ssl init procedure.
