### ISSUE TITLE
Download Exception

### ISSUE THREAD

**Issue by Charles987210** [SoftwareNetwork/sw#79]
D:\Src\tesseract-master>sw --trace configure
----------------------------------------
Starting sw...
version:
sw.client.sw version 1.0.0
git revision db82472ee934dfb8e064af419d4d8d4254b724a3
assembled on
02.06.2021 21:58:26 UTC
03.06.2021 05:58:26 �й���׼ʱ��
command line:
sw --trace configure
Checking remote version
Couldn't download db version file: Exception in file D:/dev/swst/pkg/dd/cf/960d/src/sdir/src/http/src/http.cpp:258, function download_file: url = https://raw.githubusercontent.com/SoftwareNetwork/data
base/master//db.version, curl error: Couldn't resolve host name
Host configuration: {"os":{"arch":"x86_64","kernel":"com.Microsoft.Windows.NT"}}
Registering driver: org.sw.sw.driver.cpp-0.4.1
using sw frontend for input "D:/Src/tesseract-master\\sw.cpp"
build id 0000000002A7CFA0 performing void __cdecl sw::SwBuild::loadInputs(void)
Downloading: [org.sw.demo.preshing.junction-master]/[Source Archive]
Downloading file: https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/raw/master/sw.tar.gz
Downloading file: https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/raw/master/sw.tar.gz, error: Exception in file D:/dev/swst/pkg/dd/cf/960d/src/sdir/src
/http/src/http.cpp:258, function download_file: url = https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/raw/master/sw.tar.gz, curl error: Couldn't resolve
 host name
Downloading file: https://s3-eu-west-1.amazonaws.com/software-network/data/d6/e8/0a/24/d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54355e01eb0e368a7385cf16ec9cc550c3d53c6bed18c48f90e5c5f0441
c5ac78f/sw.tar.gz
Exception in file D:/dev/cppan2/client2/src/sw/manager/storage.cpp:353, function get: Error downloading file for package: org.sw.demo.preshing.junction-master, file: Source Archive

**Comment by Charles987210** [comment]
i've solved this problem.
modify the host file..

**Comment by showersi** [comment]
I have the same problem. Where is the host file? How to modify it.

**Comment by showersi** [comment]
> i've solved this problem. modify the host file..

I have the same problem. Where is the host file? How to modify it.
