### ISSUE TITLE
Can't sign up on website

### ISSUE THREAD

**Issue by pschlan** [SoftwareNetwork/sw#85]
I can't sign up on the web site. Following error message appears:

`Failure during 'insert_user': ERROR: value too long for type character varying(255)`

My username, password and email address are all way below 255 chars.

**Comment by egorpugin** [comment]
What is your login (username or email)?

**Comment by pschlan** [comment]
It‘s pschlan

**Comment by egorpugin** [comment]
Confirmed, thank you.
I'll investigate.

**Comment by egorpugin** [comment]
Hi,

Try to sign up again.
There was an issue with salt  generation. Was incorrectly too big.

**Comment by pschlan** [comment]
Thanks, works fine now.
