### ISSUE TITLE
org.sw.demo.preshing.junction-master download failure 

### ISSUE THREAD

**Issue by showersi** [SoftwareNetwork/sw#87]
**Describe the bug**
sw configure
Downloading: [org.sw.demo.preshing.junction-master]/[Source Archive]
Exception in file D:/dev/cppan2/client2/src/sw/manager/storage.cpp:353, function get: Error downloading file for package: org.sw.demo.preshing.junction-master, file: Source Archive

**Comment by showersi** [comment]
D:\Tech\PG\OCR\tesseract-main>sw -trace configure
----------------------------------------
Starting sw...
version:
sw.client.sw version 1.0.0
git revision e006f9dc062a1f02a5344a13645a82f2acf0d931
assembled on
29.09.2021 17:16:13 UTC
30.09.2021 01:16:13 й׼ʱ
command line:
sw -trace configure
Checking remote version
Couldn't download db version file: Exception in file D:/dev/swst/pkg/dd/cf/960d/src/sdir/src/http/src/http.cpp:258, function download_file: url = https://raw.githubusercontent.com/SoftwareNetwork/database/master//db.version, curl error: Couldn't resolve host name
Host configuration: {"os":{"arch":"x86_64","kernel":"com.Microsoft.Windows.NT"}}
Registering driver: org.sw.sw.driver.cpp-0.4.1
using sw frontend for input "D:/Tech/PG/OCR/tesseract-main\\sw.cpp"
build id 0000017C9727CB30 performing void __cdecl sw::SwBuild::loadInputs(void)
Downloading: [org.sw.demo.preshing.junction-master]/[Source Archive]
Downloading file: https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/raw/master/sw.tar.gz
Downloading file: https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/raw/master/sw.tar.gz, error: Exception in file D:/dev/swst/pkg/dd/cf/960d/src/sdir/src/http/src/http.cpp:258, function download_file: url = https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/raw/master/sw.tar.gz, curl error: Couldn't resolve host name
Downloading file: https://s3-eu-west-1.amazonaws.com/software-network/data/d6/e8/0a/24/d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54355e01eb0e368a7385cf16ec9cc550c3d53c6bed18c48f90e5c5f0441c5ac78f/sw.tar.gz
Exception in file D:/dev/cppan2/client2/src/sw/manager/storage.cpp:353, function get: Error downloading file for package: org.sw.demo.preshing.junction-master, file: Source Archive

**Comment by egorpugin** [comment]
Hi,

Do you have any firewalls or something?
Can you download this file manually?
https://s3-eu-west-1.amazonaws.com/software-network/data/d6/e8/0a/24/d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54355e01eb0e368a7385cf16ec9cc550c3d53c6bed18c48f90e5c5f0441c5ac78f/sw.tar.gz

**Comment by showersi** [comment]
> Hi,
> 
> Do you have any firewalls or something? Can you download this file manually? https://s3-eu-west-1.amazonaws.com/software-network/data/d6/e8/0a/24/d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54355e01eb0e368a7385cf16ec9cc550c3d53c6bed18c48f90e5c5f0441c5ac78f/sw.tar.gz

Yes, I can successfully download it from this link.

**Comment by egorpugin** [comment]
Try to remove certs from `C:\Users\u\.sw\certs` and re-run.
Try to clear storage `C:\Users\u\.sw\storage` and re-run.

**Comment by showersi** [comment]
> Try to remove certs from `C:\Users\u\.sw\certs` and re-run. Try to clear storage `C:\Users\u\.sw\storage` and re-run.

I have tried twice but failed with same error.

**Comment by jhuix** [comment]
I also encountered this problem.

**Comment by egorpugin** [comment]
Try to add `-k` option to command line.
The reason is not clear at the moment.Curl for some reason cannot resolve the host name.

**Comment by showersi** [comment]
> Try to add `-k` option to command line. The reason is not clear at the moment.Curl for some reason cannot resolve the host name.

what is number recommended after the -k?

**Comment by egorpugin** [comment]
Sorry, use `-ignore-ssl-checks`. Not `-k`

**Comment by showersi** [comment]
> Sorry, use `-ignore-ssl-checks`. Not `-k`


Try to add "-ignore-ssl-checks" but failed with same error.



D:\Tech\PG\OCR\tesseract-main>sw -trace configure -ignore-ssl-checks
----------------------------------------
Starting sw...
version:
sw.client.sw version 1.0.0
git revision e006f9dc062a1f02a5344a13645a82f2acf0d931
assembled on
29.09.2021 17:16:13 UTC
30.09.2021 01:16:13 й׼ʱ
command line:
sw -trace configure -ignore-ssl-checks
Checking remote version
Couldn't download db version file: Exception in file D:/dev/swst/pkg/dd/cf/960d/src/sdir/src/http/src/http.cpp:258, function download_file: url = https://raw.githubusercontent.com/SoftwareNetwork/database/master//db.version, curl error: Couldn't resolve host name
Host configuration: {"os":{"arch":"x86_64","kernel":"com.Microsoft.Windows.NT"}}
Registering driver: org.sw.sw.driver.cpp-0.4.1
using sw frontend for input "D:/Tech/PG/OCR/tesseract-main\\sw.cpp"
build id 000001D1B32384D0 performing void __cdecl sw::SwBuild::loadInputs(void)
Downloading: [org.sw.demo.preshing.junction-master]/[Source Archive]
Downloading file: https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/raw/master/sw.tar.gz
Downloading file: https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/raw/master/sw.tar.gz, error: Exception in file D:/dev/swst/pkg/dd/cf/960d/src/sdir/src/http/src/http.cpp:258, function download_file: url = https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/raw/master/sw.tar.gz, curl error: Failure when receiving data from the peer
Downloading file: https://s3-eu-west-1.amazonaws.com/software-network/data/d6/e8/0a/24/d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54355e01eb0e368a7385cf16ec9cc550c3d53c6bed18c48f90e5c5f0441c5ac78f/sw.tar.gz
Exception in file D:/dev/cppan2/client2/src/sw/manager/storage.cpp:353, function get: Error downloading file for package: org.sw.demo.preshing.junction-master, file: Source Archive

**Comment by sgang81plus** [comment]
missing file:  https://github.com/sw-packages/d6e80a24d3c3d0e259fa0aa3be429ebca83d0ebb19a9fbbb1931298baa706a54/master/sw.tar.gz

encountered this problem too.

**Comment by egorpugin** [comment]
Do you run the latest client?
Try `sw --self-upgrade` and re-run.

What is your OS?
