### ISSUE TITLE
Failure to install dependencies pre tesseract install

### ISSUE THREAD

**Issue by choatix** [SoftwareNetwork/sw#89]
**Describe the bug**
Overall, I am trying to build tesseract on Windows. However, when I try to compile, I am running into a compilation issue which probably relates to Windows behaviour.

For the purposes of this report, I will directly refer to the output from the cmake command from tesseract's build script, though this directly ties in with behaviour without tesseract in a previous test.

I have attempted to run sw upgrade to no success, but this makes sense as it is a new install.

This is all from a fresh download of the client, originally done yesterday (31/01/2022)
This relates to but is not exclusive to running the tesseract section.
It appears to be an issue with the processing of variables within one of the build scripts.

Here is the main error output from running:
```
-- Setting policy CMP0091 to NEW
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
Configuring tesseract version 5.0.1-9-g31a968...
-- IPO / LTO supported
CMAKE_SYSTEM_PROCESSOR=<AMD64>
-- sw: processing dependencies
[167/174] [config pch]
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:825, function execute1: When executing: [config pch]
C:\Users\{}\.sw\storage\pkg\83\e1\d224\src\sdir\src\sw/core/build.h(80): error C3533: a parameter cannot have a type that contains 'auto'
command failed: exit code = 2
Total errors: 1
sw command: C:/DevTools/sw-master-windows-client/sw.exe -static -platform x64 -compiler msvc-19.27 -d C:/Other Projects/tesseract/build/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps C:/Other Projects/tesseract/build/.sw/cmake/sw.txt -cmake-file-version 6
```

```
sw -trace
Starting sw...
version:
sw.client.sw version 1.0.0
git revision 8d2a117e66deea583b45815150e78d76444b7137
assembled on
20.12.2021 11:02:00 UTC
20.12.2021 11:02:00 GMT Standard Time
command line:
C:\DevTools\sw-master-windows-client\sw.exe -trace
No command was issued

```

**Comment by egorpugin** [comment]
Hi,

This is the sw side issue.
You have to install VS2022 (or probably VS2019 at least) in order to compile sw build scripts.
