### ISSUE TITLE
Static linking tesseract

### ISSUE THREAD

**Issue by EugW** [SoftwareNetwork/sw#9]
D:\Evgeny\Documents\DEV\sw\tesseract>sw -version
sw.client.sw version 0.3.1
git revision d5fa93141aad4f24e56c56338006d09c93717340 plus 18 modified files
assembled on 10.08.2019 23:24:55 Russia TZ 4 Standard Time

Now it creates two folders
![image](https://user-images.githubusercontent.com/22213508/62830956-f5cfd000-bc30-11e9-9e3a-62a1c044e563.png)
With this contents
![image](https://user-images.githubusercontent.com/22213508/62830967-1ac44300-bc31-11e9-8529-db2acca66b98.png)
![image](https://user-images.githubusercontent.com/22213508/62830968-21eb5100-bc31-11e9-9dc3-38794854f74b.png)
Which one should I use to link tess to Qt?
I used fat one (76MB, second screenshot), but compiler says that leptonica's methods undefined
My configuration 
![image](https://user-images.githubusercontent.com/22213508/62830983-61b23880-bc31-11e9-8588-f481cf5b5842.png)
(Old linking is commented)
The first error is the inability to compile in debug mode
![image](https://user-images.githubusercontent.com/22213508/62830992-b0f86900-bc31-11e9-8153-209558d033e4.png)
Ok, when I switch to release mode compiler says that leptonica's methods undefined
![image](https://user-images.githubusercontent.com/22213508/62831002-d1282800-bc31-11e9-90b6-b7e94c3bb8c9.png)

Oh sorry, when I pick lib from other folder it works fine

**Comment by egorpugin** [comment]
Check cfg.json for build info. You should not mix debug/release builds.
