### ISSUE TITLE
ception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:1486, function resolveExecutable: which and where were not found, cannot resolve executable: clang-cl

### ISSUE THREAD

**Issue by sutiao311** [SoftwareNetwork/sw#90]
sw -trace configure
----------------------------------------
Starting sw...
version:
sw.client.sw version 1.0.0
git revision 8d2a117e66deea583b45815150e78d76444b7137
assembled on
20.12.2021 11:02:00 UTC
20.12.2021 19:02:00 й׼ʱ

Detected target: com.Microsoft.Windows.SDK.um-10.0.19041.0: {"os":{"arch":"arm","kernel":"com.Microsoft.Windows.NT"}}
Detected target: com.Microsoft.Windows.SDK.um-10.0.19041.0: {"os":{"arch":"aarch64","kernel":"com.Microsoft.Windows.NT"}}
Include dir "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\km" not found for library: km
Detected target: com.Microsoft.Windows.SDK.winrt-10.0.19041.0: {"os":{"arch":"x86_64","kernel":"com.Microsoft.Windows.NT"}}
Detected target: com.Microsoft.Windows.SDK.winrt-10.0.19041.0: {"os":{"arch":"x86","kernel":"com.Microsoft.Windows.NT"}}Detected target: com.Microsoft.Windows.SDK.winrt-10.0.19041.0: {"os":{"arch":"arm","kernel":"com.Microsoft.Windows.NT"}}Detected target: com.Microsoft.Windows.SDK.winrt-10.0.19041.0: {"os":{"arch":"aarch64","kernel":"com.Microsoft.Windows.NT"}}
Detected target: com.Microsoft.Windows.SDK.cppwinrt-10.0.19041.0: {"os":{"arch":"x86_64","kernel":"com.Microsoft.Windows.NT"}}
Detected target: com.Microsoft.Windows.SDK.cppwinrt-10.0.19041.0: {"os":{"arch":"x86","kernel":"com.Microsoft.Windows.NT"}}
Detected target: com.Microsoft.Windows.SDK.cppwinrt-10.0.19041.0: {"os":{"arch":"arm","kernel":"com.Microsoft.Windows.NT"}}
Detected target: com.Microsoft.Windows.SDK.cppwinrt-10.0.19041.0: {"os":{"arch":"aarch64","kernel":"com.Microsoft.Windows.NT"}}
Detected target: com.Microsoft.Windows.rc-10.0.10011.16384: {"os":{"kernel":"com.Microsoft.Windows.NT"}}
Detected program: C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe
Detected target: com.Microsoft.Windows.mc-10.0.19041: {"os":{"kernel":"com.Microsoft.Windows.NT"}}
Detected program: C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\mc.exe
Found Windows Kit 8.1 at C:/Program Files (x86)/Windows Kits/8.1
Include dir "C:\\Program Files (x86)\\Windows Kits\\8.1\\Include\\um" not found for library: um
Include dir "C:\\Program Files (x86)\\Windows Kits\\8.1\\Include\\km" not found for library: km
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:1486, function resolveExecutable: which and where were not found, cannot resolve executable: clang-cl

**Comment by egorpugin** [comment]
Hi, 

Are you running from powershell or cmd? Maybe this is WSL or mingw64 console?
It seems that you does not have `where` or `which` commands.
Try to enter them.

**Comment by sutiao311** [comment]
running from powershell。

    static const auto p_which = primitives::resolve_executable("which");
    static const auto p_where = primitives::resolve_executable("where");

    if (p_which.empty() && p_where.empty())
        throw SW_RUNTIME_ERROR("which and where were not found, cannot resolve executable: " + to_string(in.u8string()));

   What do I have to do to run the where or which command！！！

**Comment by egorpugin** [comment]
Just run `where` or `which` in powershell, post output.
Try to install `where` command.

**Comment by egorpugin** [comment]
Also try to run sw from `cmd`.
