### ISSUE TITLE
WS fails with DevStudio 17, MSVC 14.16.27023

### ISSUE THREAD

**Issue by mbrunecky** [SoftwareNetwork/sw#93]
**Describe the bug**
While using cmake on tesseract 5.1, WS fails to compile (multiple files) with MSVC reporting:
C:\Users\mbrunecky\.sw\storage\pkg\e2\99\efe6\src\sdir\src\string\include\primitives/string.h(42): error C2039: 'u8string': is not a member of 'std'

**Expected behavior**
I do not know why WS is downloading, checking and compiling hundreds of packages/files,. However, per tesseract documentation  invoking the following sequence should produce a DevStudio solution for tesseract development:

```
git clone https://github.com/tesseract-ocr/tesseract tesseract
cd tessersact
mkdir build
cd build
cmake ...
```

But instead, it fails with hundreds of errors.

**To Reproduce**

```
cd tesseract\build
cmake ..

```
**Information:**
 - sw.client.sw version 1.0.0
git revision 8d2a117e66deea583b45815150e78d76444b7137
assembled on
20.12.2021 11:02:00 UTC
20.12.2021 04:02:00 Mountain Standard Time

 - Windows 10
 - HP 440 workstation 
 
Dev Studio 17, repeatedly updated and 'repaired' (making sure it is not damaged).
As far as I can tell, the Standard Library (part of DevStudio 17) does not define/recognize std:u8string used in multiple WS files.

**Comment by egorpugin** [comment]
Hi,

Please see my comment https://github.com/tesseract-ocr/tesseract/issues/3772#issuecomment-1073215969
