### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by sunnyfulin** [SoftwareNetwork/sw#95]
**Describe the bug**
I got the latest sw client (run `sw --self-upgrade`)  and then:
run .\sw install
and I got the output text:
PS D:\Z_Work_Station> .\sw install
Downloading database from origin remote
copy_file: ϵͳҲָ·: "C:\Users\fulin\AppData\Local\Temp\sw\42f1-7163-8797-b6d3\database-master\README.md", "C:\Users\fulin\.sw\storage\etc\sw\database\1\remote\origin\repository\README.md"

![屏幕截图 2022-07-02 115603](https://user-images.githubusercontent.com/15729129/176985635-3a533481-c8c0-4799-aa9f-d1dfb7ddf173.jpg)

**Comment by egorpugin** [comment]
Hi,

Try to remove the file manually.
I also noticed such issue on CIs.

I'll do a possible fix and upload new binaries, try it when they are available.

**Comment by egorpugin** [comment]
See https://github.com/SoftwareNetwork/sw/commit/e6bfb196666b3ea5ab8ed9e418599d2a6086101a

**Comment by egorpugin** [comment]
Probably fixed with the latest build.
